# Generated by Django 6.0.4 on 2026-05-04 19:35

import django.db.models.deletion
import plugins.installed.digital_products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_canonical_url_product_focus_keyword_and_more'),
        ('orders', '0006_cart_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=plugins.installed.digital_products.models._new_token, help_text='Random URL-safe token used in the public download URL.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('downloads_used', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='digital_pro_order_i_4b91d4_idx')],
            },
        ),
    ]
