# Generated by Django 6.0.4 on 2026-05-05 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='How merchants refer to this mailbox.', max_length=120)),
                ('email_address', models.EmailField(help_text='The full address — used as the From header on outbound mail.', max_length=254, unique=True)),
                ('provider', models.CharField(choices=[('imap', 'IMAP / SMTP (generic)'), ('gmail', 'Gmail (IMAP)'), ('outlook', 'Outlook / Office 365 (IMAP)'), ('fastmail', 'Fastmail (IMAP)'), ('other', 'Other')], default='imap', max_length=20)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(max_length=255)),
                ('imap_password', models.CharField(max_length=255)),
                ('imap_folder', models.CharField(default='INBOX', max_length=80)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Sent')], db_index=True, max_length=3)),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='RFC822 Message-ID — used to dedupe inbound messages.', max_length=255)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, max_length=255)),
                ('thread_key', models.CharField(blank=True, db_index=True, help_text='Normalised subject + counterparty — groups a thread.', max_length=255)),
                ('from_address', models.CharField(db_index=True, max_length=320)),
                ('to_addresses', models.TextField(blank=True, help_text='Comma-separated.')),
                ('cc_addresses', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.mailaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_mail_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-sent_at', '-created_at'],
                'indexes': [models.Index(fields=['account', '-received_at'], name='crm_mailmes_account_21a1b5_idx'), models.Index(fields=['customer', '-received_at'], name='crm_mailmes_custome_773c43_idx')],
            },
        ),
    ]
