# Generated by Django 6.0.5 on 2026-05-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_lindamemory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lindamemory',
            new_name='assistant_l_scope_0226e5_idx',
            old_name='assistant_l_scope_4dfaf8_idx',
        ),
    ]
