# Generated by Django 6.0.5 on 2026-06-07 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_rename_assistant_l_scope_4dfaf8_idx_assistant_l_scope_0226e5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('system_prompt_prelude', models.TextField(blank=True)),
                ('tool_names', models.JSONField(default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='distilled', max_length=200)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
