# Generated by Django 6.0.5 on 2026-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_learnedskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedskill',
            name='failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnedskill',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnedskill',
            name='successes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnedskill',
            name='uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
