# Generated by Django 6.0.5 on 2026-06-07 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_learnedskill_failures_learnedskill_last_used_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=120)),
                ('kind', models.CharField(default='tool', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('target_path', models.CharField(blank=True, max_length=300)),
                ('source', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], db_index=True, default='draft', max_length=12)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
