# Generated by Django 6.0.5 on 2026-06-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_codeproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproposal',
            name='consensus',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
