# Generated by Django 6.0.5 on 2026-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_codeproposal_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproposal',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeproposal',
            name='applied_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='codeproposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeproposal',
            name='approver',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
