# Generated by Django 6.0.5 on 2026-06-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_codeproposal_applied_at_codeproposal_applied_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
