# Generated by Django 6.0.5 on 2026-06-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_assistantmessage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lindamemory',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
