# Generated by Django 6.0.5 on 2026-07-03 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_lindamemory_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantBriefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=12)),
                ('body', models.TextField(blank=True)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
