# Generated by Django 6.0.5 on 2026-07-05 18:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agent_core', '0002_backgroundagent'),
        ('assistant', '0011_assistantbriefing'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsProposal',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('source', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=list)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('proposed', 'Proposed'),
                            ('approved', 'Approved'),
                            ('applied', 'Applied'),
                            ('rejected', 'Rejected'),
                            ('expired', 'Expired'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='proposed',
                        max_length=20,
                    ),
                ),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'agent_run',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ops_proposals',
                        to='agent_core.agentrun',
                    ),
                ),
                (
                    'approved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='approved_ops_proposals',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'target_ct',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
