# Generated by Django 6.0.5 on 2026-07-20 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_opsproposal'),
        ('core', '0021_agentrun_agentapprovalrequest_agentstep_and_more'),
    ]

    operations = [
        # State-only: the tables/indexes already exist under their original
        # agent_core_* names (db_table pins them) — zero SQL (ADR 0034).
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.AlterField(
                model_name='opsproposal',
                name='agent_run',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_proposals', to='core.agentrun'),
            ),
            ],
            database_operations=[],
        ),
    ]
