# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_alter_opsproposal_agent_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, choices=[('', 'Use server default'), ('janus', 'Janus (store agent)'), ('legacy', 'In-process fallback')], default='', max_length=16)),
                ('model', models.CharField(blank=True, help_text='Janus model id. Blank uses JANUS_INFERENCE_MODEL / auto.', max_length=120)),
                ('auto_approve', models.BooleanField(default=False, help_text='Let Janus run tool calls without a prompt (yolo). Off by default.')),
                ('timeout_s', models.PositiveSmallIntegerField(blank=True, help_text='Seconds per turn. Blank uses server default (55, under gunicorn).', null=True)),
                ('mcp_url', models.CharField(blank=True, max_length=400)),
                ('mcp_token', models.CharField(blank=True, max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Janus settings',
                'verbose_name_plural': 'Janus settings',
            },
        ),
    ]
