# Generated by Django 6.0.5 on 2026-09-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_alter_opsproposal_agent_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanusLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('path', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('memory', 'Memory notes'), ('journal', 'Memory journal'), ('skill', 'Skill file'), ('lesson', 'Lessons')], db_index=True, max_length=16)),
                ('content', models.TextField()),
                ('conversation_key', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope', 'path'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'path'), name='assistant_janus_learning_scope_path')],
            },
        ),
    ]
