# Generated by Django 6.0.4 on 2026-04-25 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('to_path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)')], default=301)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['from_path'],
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=500, unique=True)),
                ('changefreq', models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='weekly', max_length=10)),
                ('priority', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True, max_length=600)),
                ('og_type', models.CharField(choices=[('website', 'Website'), ('product', 'Product'), ('article', 'Article'), ('book', 'Book')], default='website', max_length=20)),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='summary | summary_large_image | app | player', max_length=20)),
                ('canonical_url', models.URLField(blank=True, max_length=600)),
                ('robots', models.CharField(choices=[('index, follow', 'Index, follow'), ('noindex, follow', 'Noindex, follow'), ('index, nofollow', 'Index, nofollow'), ('noindex, nofollow', 'Noindex, nofollow')], default='index, follow', max_length=40)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated. Most engines ignore this; included for completeness.', max_length=320)),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Extra JSON-LD properties merged into the auto-generated payload.')),
                ('auto_filled', models.BooleanField(default=False, help_text='True if filled by AI; False if merchant-edited.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seometa_content_f52eba_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
