# Generated by Django 6.0.4 on 2026-04-26 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_target', models.CharField(blank=True, max_length=500)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-hit_count', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSeoSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('organization_logo_url', models.URLField(blank=True, max_length=600)),
                ('default_og_image', models.URLField(blank=True, max_length=600)),
                ('twitter_handle', models.CharField(blank=True, help_text='Without @', max_length=50)),
                ('twitter_card_default', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary (large image)')], default='summary_large_image', max_length=20)),
                ('facebook_url', models.URLField(blank=True, max_length=600)),
                ('instagram_url', models.URLField(blank=True, max_length=600)),
                ('linkedin_url', models.URLField(blank=True, max_length=600)),
                ('youtube_url', models.URLField(blank=True, max_length=600)),
                ('tiktok_url', models.URLField(blank=True, max_length=600)),
                ('google_site_verification', models.CharField(blank=True, max_length=120)),
                ('bing_verification', models.CharField(blank=True, max_length=120)),
                ('pinterest_verification', models.CharField(blank=True, max_length=120)),
                ('facebook_domain_verification', models.CharField(blank=True, max_length=120)),
                ('enable_sitelinks_search', models.BooleanField(default=True)),
                ('llms_txt_enabled', models.BooleanField(default=True, help_text='Serve /llms.txt for LLM crawlers (OpenAI, Anthropic, Perplexity, Google).')),
                ('llms_txt_intro', models.TextField(blank=True, help_text='Optional intro paragraph at the top of /llms.txt.')),
                ('ai_shopping_feed_enabled', models.BooleanField(default=True, help_text='Serve /ai/products.json — schema.org Product feed for AI shopping crawlers.')),
                ('title_template', models.CharField(default='{title} — {site_name}', help_text='Variables: {title}, {site_name}, {category}', max_length=200)),
                ('title_max_length', models.PositiveSmallIntegerField(default=60)),
                ('description_max_length', models.PositiveSmallIntegerField(default=155)),
                ('noindex_query_params', models.JSONField(blank=True, default=list, help_text='Auto-add noindex on URLs that contain any of these query params (e.g. ["q","sort"])')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site SEO settings',
            },
        ),
        migrations.CreateModel(
            name='TrackedKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=200)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('locale', models.CharField(default='en-US', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['keyword'],
                'unique_together': {('keyword', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='SeoAuditResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=64)),
                ('score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('issues', models.JSONField(default=list, help_text='List of {code, severity, message} dicts.')),
                ('suggestions', models.JSONField(default=list)),
                ('audited_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['score'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seoaudi_content_23a77f_idx'), models.Index(fields=['score', '-audited_at'], name='seo_seoaudi_score_add09c_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
