# Generated by Django 6.0.5 on 2026-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_notfoundlog_siteseosettings_trackedkeyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteseosettings',
            name='ai_answer_block_enabled',
            field=models.BooleanField(default=False, help_text='Render a "Key facts / In short" answer block on product pages — a quotable TL;DR + spec table that AI answer engines (ChatGPT, Perplexity, AI Overviews) lift on-page. Off by default; needs an AI answer (seo.ai_answer metafield) or book metafields to show.'),
        ),
    ]
