# Generated by Django 6.0.5 on 2026-06-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_siteseosettings_ai_answer_block_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteseosettings',
            name='jsonld_organization',
            field=models.BooleanField(default=True, help_text='Emit Organization JSON-LD site-wide.'),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='jsonld_product',
            field=models.BooleanField(default=True, help_text='Emit Product JSON-LD on product pages.'),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='jsonld_reviews',
            field=models.BooleanField(default=True, help_text='Include aggregateRating + Review snippets inside Product JSON-LD.'),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='jsonld_website',
            field=models.BooleanField(default=True, help_text='Emit WebSite JSON-LD (+ sitelinks search box).'),
        ),
    ]
