# Generated by Django 6.0.5 on 2026-06-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_siteseosettings_jsonld_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometa',
            name='schema_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Visual schema editor entries [{type, data}, …] (FAQ, HowTo, Event, …). Built into standalone <script type="application/ld+json"> blocks at render time — distinct from the merged structured_data dict above.'),
        ),
    ]
