# Generated by Django 6.0.5 on 2026-08-18 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0005_seometa_schema_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=64)),
                ('old_path', models.CharField(db_index=True, max_length=500)),
                ('new_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='redirect',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact path'), ('prefix', 'Path prefix'), ('regex', 'Regular expression')], db_index=True, default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='redirect',
            name='source',
            field=models.CharField(choices=[('manual', 'Added by hand'), ('auto_slug', 'Created automatically when a slug changed'), ('import', 'Imported from CSV'), ('404_fix', 'Created from the 404 log'), ('agent', 'Created by an assistant')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='seometa',
            name='ai_answer',
            field=models.TextField(blank=True, help_text='A quotable, factual TL;DR an answer engine can lift verbatim. Powers the on-page key-facts block and disambiguatingDescription. Was the seo.ai_answer metafield; read-through fallback remains.', max_length=600),
        ),
        migrations.AddField(
            model_name='seometa',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text="The query this page is written for. Internal only — it drives the panel's checks and the SEO score, and is never emitted as markup.", max_length=120),
        ),
        migrations.AddField(
            model_name='seometa',
            name='provenance',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field origin: {"title": "merchant"|"ai"|"template"|"migrated"}. Lets the panel show where a value came from, and lets a bulk template or AI pass skip anything the merchant wrote by hand.'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='robots_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced robots directives beyond index/follow — any of max_snippet (int), max_image_preview ("none"|"standard"|"large"), max_video_preview (int), nosnippet (bool), noimageindex (bool), unavailable_after (ISO 8601 date). These are also what gates how much of the page may appear inside AI Overviews / AI Mode.'),
        ),
        migrations.AddField(
            model_name='seometa',
            name='sitemap_include',
            field=models.BooleanField(blank=True, help_text='Tri-state override: NULL keeps the platform default for this page kind, True forces the URL into the sitemap, False keeps it out. A noindex page is never included regardless.', null=True),
        ),
        migrations.AddField(
            model_name='seometa',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='seometa',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='auto_redirect_on_slug_change',
            field=models.BooleanField(default=True, help_text='When a product, category, collection or page is renamed, keep the old URL working with a 301 to the new one. Off means renaming a page breaks every existing link to it.'),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='block_homepage_redirects',
            field=models.BooleanField(default=True, help_text='Refuse redirects that point at the homepage. Bulk-redirecting dead URLs to "/" reads as a soft 404 to search engines and loses the page rather than moving it — leave this on unless you mean it.'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='from_path',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, 'Permanent (301)'), (302, 'Temporary (302)'), (307, 'Temporary, keep method (307)'), (308, 'Permanent, keep method (308)'), (410, 'Gone (410) — removed for good')], default=301),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='keywords',
            field=models.CharField(blank=True, help_text='LEGACY. Was emitted as <meta name="keywords">, which every major engine has ignored since 2009 — and the panel that wrote it was labelled "internal", so a merchant\'s private focus keyword was published on the page. Nothing reads this now; use focus_keyword.', max_length=320),
        ),
        migrations.AddConstraint(
            model_name='redirect',
            constraint=models.UniqueConstraint(fields=('from_path', 'match_type'), name='seo_redirect_unique_rule'),
        ),
        migrations.AddField(
            model_name='slughistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='slughistory',
            index=models.Index(fields=['content_type', 'object_id'], name='seo_slughis_content_225708_idx'),
        ),
    ]
