# Generated by Django 6.0.5 on 2026-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_slughistory_redirect_match_type_redirect_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometa',
            name='og_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('product', 'Product'), ('article', 'Article'), ('book', 'Book')], default='', max_length=20),
        ),
    ]
