# Generated by Django 6.0.5 on 2026-08-19 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_alter_seometa_og_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('param', models.CharField(help_text='Query parameter name. A trailing * matches a family, e.g. utm_*', max_length=64, unique=True)),
                ('policy', models.CharField(choices=[('consolidate', 'Keep indexable, drop from the canonical'), ('noindex', 'No-index this page (self-canonical)'), ('allowlist', 'Index only the listed values'), ('block', 'Block in robots.txt')], default='consolidate', max_length=16)),
                ('allowed_values', models.JSONField(blank=True, default=list, help_text='Values that stay indexable, for the "index only the listed values" policy.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Index rule',
                'ordering': ['param'],
            },
        ),
    ]
