# Generated by Django 6.0.5 on 2026-08-20 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_indexrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('product', 'Products'), ('listing', 'Category & collection pages'), ('article', 'Journal posts'), ('page', 'CMS pages'), ('static', 'Static pages')], db_index=True, max_length=20)),
                ('field', models.CharField(choices=[('title', 'Meta title'), ('description', 'Meta description')], default='title', max_length=20)),
                ('scope', models.CharField(blank=True, default='', help_text='Category slug to narrow this rule to; empty = every page of the kind.', max_length=200)),
                ('template', models.TextField(help_text='Pattern with {tokens} — e.g. {name} — buy online | {site_name}')),
                ('mode', models.CharField(choices=[('empty_only', 'Fill empty fields only'), ('all', 'Override everything of this kind')], default='empty_only', max_length=20)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'field', 'priority', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'field', 'scope'), name='seo_template_one_per_scope')],
            },
        ),
    ]
