# Generated by Django 6.0.4 on 2026-04-26 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_storesettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='webhooks_ui_endpoin_a3db0c_idx'), models.Index(fields=['status', 'next_retry_at'], name='webhooks_ui_status_d4701f_idx')],
            },
        ),
    ]
