# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('dlq', 'Dead-letter (max retries)')], db_index=True, default='queued', max_length=12),
        ),
    ]
