# Generated by Django 6.0.5 on 2026-06-28 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
        ('dynamic_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicblock',
            name='strategy',
            field=models.CharField(choices=[('for_you', 'For you (personalized blend)'), ('manual', 'Manual / rule (filtered catalog)'), ('recently_viewed', 'Recently viewed'), ('related', 'Related to this product'), ('bought_together', 'Frequently bought together'), ('probability_grid', 'Dynamic Probability Grid')], default='for_you', help_text='How products are chosen.', max_length=20),
        ),
        migrations.CreateModel(
            name='DynamicGridItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('cover_image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('purchase_probability', models.FloatField(db_index=True, default=0.0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_grid_item', to='catalog.product')),
            ],
            options={
                'ordering': ['-purchase_probability'],
            },
        ),
    ]
