# Generated by Django 6.0.5 on 2026-07-06 23:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0014_product_additional_categories'),
        ('dynamic_products', '0002_alter_dynamicblock_strategy_dynamicgriditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditArm',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'segment',
                    models.CharField(
                        db_index=True,
                        help_text='Anonymous visitor segment, e.g. "mobile:evening:anon".',
                        max_length=64,
                    ),
                ),
                ('alpha', models.FloatField(default=1.0)),
                ('beta', models.FloatField(default=1.0)),
                ('trials', models.PositiveIntegerField(default=0)),
                ('reward', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bandit_arms',
                        to='catalog.product',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['segment', 'product'], name='dynbandit_segment_idx')
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('product', 'segment'), name='dynbandit_product_segment'
                    )
                ],
            },
        ),
    ]
