# Generated by Django 6.0.5 on 2026-07-06 23:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dynamic_products', '0004_alter_dynamicblock_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandisingProposal',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('enable_autopilot', 'Turn on Autopilot'),
                            ('provision_block', 'Add a merchandising block'),
                            ('feature_products', 'Feature high-propensity products'),
                            ('winning_strategy', 'Experiment result'),
                            ('insight', 'Merchandising insight'),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('rationale', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(db_index=True, max_length=200)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('proposed', 'Proposed'),
                            ('approved', 'Approved'),
                            ('dismissed', 'Dismissed'),
                        ],
                        db_index=True,
                        default='proposed',
                        max_length=16,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='dynprop_status_idx')
                ],
            },
        ),
    ]
