# Generated by Django 6.0.5 on 2026-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_products', '0006_alter_dynamicblock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblock',
            name='columns',
            field=models.PositiveSmallIntegerField(default=4, help_text='Items per row when the layout is Grid (2–6).'),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='diversity_cap',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override the max items per category in the head. Blank = default.', null=True),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='exclude_out_of_stock',
            field=models.BooleanField(default=False, help_text='Hide products with zero available stock (needs the inventory plugin).'),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='exclude_purchased',
            field=models.BooleanField(default=False, help_text='Hide products the signed-in visitor has already bought.'),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='excluded_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Product ids to always hide from this block.'),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='exploration_rate',
            field=models.FloatField(blank=True, help_text='Override the bandit exploration rate (0–1). Blank = default.', null=True),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('grid', 'Grid')], default='carousel', max_length=16),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='pinned_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Product ids to force to the front, in order.'),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only show products at/below this price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only show products at/above this price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='segment_override',
            field=models.CharField(blank=True, help_text='Force a bandit segment for everyone (advanced). Blank = per-visitor.', max_length=64),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamicblock',
            name='show_reason',
            field=models.BooleanField(default=False, help_text='Show a short "why" label under each product (e.g. “Trending”).'),
        ),
    ]
