# Generated by Django 6.0.5 on 2026-07-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_products', '0007_dynamicblock_columns_dynamicblock_diversity_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblock',
            name='surface',
            field=models.CharField(blank=True, choices=[('home_hero', 'Home — hero carousel (free pick)'), ('home_featured', 'Home — “New & notable” grid (free pick)'), ('home_staff_picks', 'Home — staff picks grid (reorder)'), ('plp_default', 'Shop — default product list (reorder, per page)'), ('category_list', 'Category pages (reorder, per page)'), ('collection_list', 'Collection pages (reorder, per page)'), ('section_featured', 'Page-builder “Featured products” sections (reorder)')], db_index=True, default='', help_text='Existing theme placeholder this block takes over (hero, featured grid, PLP order, …). Leave empty for a normal slot block.', max_length=40),
        ),
        migrations.AlterField(
            model_name='dynamicblock',
            name='slot',
            field=models.CharField(blank=True, choices=[('home_above_grid', 'Home — above the grid'), ('home_below_grid', 'Home — below the grid'), ('home_after_rails', 'Home — after the collection rails'), ('pdp_below_price', 'Product page — below price'), ('pdp_below_form', 'Product page — below add-to-cart'), ('pdp_above_long_description', 'Product page — above description'), ('cart_summary_extra', 'Cart — order summary'), ('checkout_extra', 'Checkout — below the form'), ('order_receipt_extra', 'Order confirmation — below the receipt'), ('global_below_body', 'Every page — end of body')], db_index=True, help_text='Where on the storefront this block renders (leave empty for a surface takeover).', max_length=40),
        ),
    ]
