# Generated by Django 6.0.5 on 2026-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_products', '0008_dynamicblock_surface_alter_dynamicblock_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicblock',
            name='strategy',
            field=models.CharField(choices=[('smart', 'Smart (probability + trend + session, explainable)'), ('for_you', 'For you (personalized blend)'), ('manual', 'Manual / rule (filtered catalog)'), ('recently_viewed', 'Recently viewed'), ('related', 'Related to this product'), ('bought_together', 'Frequently bought together'), ('probability_grid', 'Dynamic Probability Grid'), ('autopilot', 'Autopilot (self-optimizing, per-visitor)'), ('trending', 'Trending now'), ('new_arrivals', 'New arrivals'), ('best_sellers', 'Best sellers'), ('on_sale', 'On sale'), ('similar_price', 'Similar price (product page)')], default='for_you', help_text='How products are chosen.', max_length=20),
        ),
    ]
