# Generated by Django 6.0.5 on 2026-07-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_products', '0009_alter_dynamicblock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicblock',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show the product name under each cover (off = image-only grid).'),
        ),
    ]
