# Generated by Django 6.0.5 on 2026-06-03 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('contributors', models.JSONField(blank=True, default=list)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('imprint', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, default='en', max_length=20)),
                ('series', models.CharField(blank=True, max_length=200)),
                ('series_position', models.CharField(blank=True, max_length=40)),
                ('synopsis', models.TextField(blank=True)),
                ('print_type', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('mass_market', 'Mass-market paperback'), ('board_book', 'Board book'), ('spiral', 'Spiral / wire-o'), ('leather', 'Leather / cloth bound'), ('ebook', 'E-book'), ('audiobook', 'Audiobook')], default='paperback', max_length=20)),
                ('paper_type', models.CharField(blank=True, choices=[('standard', 'Standard white'), ('cream', 'Cream / off-white'), ('coated_gloss', 'Coated gloss'), ('coated_matte', 'Coated matte'), ('uncoated', 'Uncoated'), ('recycled', 'Recycled')], max_length=20)),
                ('binding', models.CharField(blank=True, max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('spine_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_pdf', models.FileField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Book product',
                'verbose_name_plural': 'Book products',
            },
        ),
    ]
