# Generated by Django 6.0.5 on 2026-06-04 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0002_migrate_book_metafields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTaxonomyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy', models.CharField(choices=[('author', 'Author'), ('publisher', 'Publisher'), ('series', 'Series'), ('imprint', 'Imprint')], db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_taxonomies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book taxonomy term',
                'verbose_name_plural': 'Book taxonomy terms',
                'unique_together': {('taxonomy', 'slug')},
            },
        ),
    ]
