# Generated by Django 6.0.5 on 2026-06-13 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0003_booktaxonomyterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTaxonomyRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy', models.CharField(choices=[('author', 'Author'), ('publisher', 'Publisher'), ('series', 'Series'), ('imprint', 'Imprint')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_taxonomies/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book taxonomy root page',
                'verbose_name_plural': 'Book taxonomy root pages',
            },
        ),
    ]
