# Generated by Django 6.0.5 on 2026-07-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0007_backfill_remaining_books_to_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='book_product.bookproduct'),
        ),
    ]
