# Generated by Django 6.0.5 on 2026-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0008_bookproduct_translation_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktaxonomyroot',
            name='taxonomy',
            field=models.CharField(choices=[('author', 'Author'), ('publisher', 'Publisher'), ('series', 'Series'), ('imprint', 'Imprint'), ('genre', 'Genre'), ('topic', 'Topic')], max_length=20, unique=True),
        ),
    ]
