# Generated by Django 6.0.5 on 2026-06-14 00:58

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPopup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('headline', models.CharField(default='Join our newsletter', max_length=200)),
                ('body', models.TextField(blank=True, default='Get the latest news and offers.')),
                ('button_label', models.CharField(default='Subscribe', max_length=60)),
                ('success_message', models.CharField(default='Thanks — check your inbox!', max_length=200)),
                ('trigger', models.CharField(choices=[('immediate', 'On page load'), ('time_delay', 'After N seconds'), ('exit_intent', 'On exit intent'), ('scroll_depth', 'After scrolling N%')], default='time_delay', max_length=12)),
                ('trigger_value', models.PositiveIntegerField(default=5, help_text='Seconds (time_delay) or percent (scroll_depth).')),
                ('frequency', models.CharField(choices=[('once', 'Once per visitor'), ('daily', 'Once per day'), ('every_visit', 'Every visit')], default='once', max_length=12)),
                ('audience', models.CharField(choices=[('all', 'All visitors'), ('new', 'New visitors'), ('returning', 'Returning visitors')], default='all', max_length=10)),
                ('incentive', models.CharField(blank=True, help_text='e.g. "10% off your first order".', max_length=120)),
                ('coupon_code', models.CharField(blank=True, max_length=60)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='pending', max_length=12)),
                ('source', models.CharField(choices=[('popup', 'Signup popup'), ('form', 'Storefront form'), ('checkout', 'Checkout'), ('manual', 'Manual / dashboard'), ('import', 'Import')], default='popup', max_length=12)),
                ('confirm_token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='newsletter__status_a507fa_idx')],
            },
        ),
    ]
