# Generated by Django 6.0.5 on 2026-07-18 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('campaign', 'Campaign'), ('winback', 'Win-back'), ('test', 'Test send')], default='campaign', max_length=12)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ok', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='marketing.emailcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'email'], name='newsletter__campaig_f25be1_idx'), models.Index(fields=['kind', 'email', '-created_at'], name='newsletter__kind_c6bcfa_idx')],
            },
        ),
    ]
