# Generated by Django 6.0.4 on 2026-04-24 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Config',
                'verbose_name_plural': 'Theme Configs',
            },
        ),
    ]
