# Generated by Django 6.0.4 on 2026-04-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Morph Store', max_length=200)),
                ('store_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('primary_currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(default='US', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('ai_provider', models.CharField(default='openai', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('social_links', models.JSONField(default=dict)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
