# Generated by Django 6.0.4 on 2026-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='Morpheus Store', max_length=200),
        ),
    ]
