# Generated by Django 6.0.4 on 2026-04-24 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storesettings_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='The destination URL to POST event payloads')),
                ('secret', models.CharField(blank=True, help_text='Used for HMAC signature verification', max_length=255)),
                ('events', models.JSONField(default=list, help_text="List of event strings to subscribe to, e.g. ['order.placed']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
