# Generated by Django 6.0.4 on 2026-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='default_from_email',
            field=models.CharField(blank=True, help_text='e.g. noreply@dotbooks.shop', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.resend.com', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
