# Generated by Django 6.0.4 on 2026-04-26 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storesettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(db_index=True, max_length=3)),
                ('quote_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='core_exchan_base_cu_0ffd9e_idx')],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
    ]
