# Generated by Django 6.0.4 on 2026-04-26 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storechannel',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='storechannel',
            name='country_codes',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of ISO countries this channel serves (empty = global).'),
        ),
        migrations.AddField(
            model_name='storechannel',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code; prices use this.', max_length=3),
        ),
        migrations.AddField(
            model_name='storechannel',
            name='default_country',
            field=models.CharField(default='US', help_text='ISO 3166-1 alpha-2; used for tax/shipping defaults.', max_length=2),
        ),
        migrations.AddField(
            model_name='storechannel',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='storechannel',
            name='slug',
            field=models.SlugField(default='default', max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='ProductChannelListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('visible_in_listings', models.BooleanField(default=True)),
                ('available_for_purchase', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='core.storechannel')),
                ('product_ct', models.ForeignKey(limit_choices_to={'app_label': 'catalog', 'model': 'product'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'is_published'], name='core_produc_channel_f87245_idx'), models.Index(fields=['product_ct', 'product_id'], name='core_produc_product_3ebb47_idx')],
                'unique_together': {('channel', 'product_ct', 'product_id')},
            },
        ),
    ]
