# Generated by Django 6.0.5 on 2026-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_storechannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='product_placeholder_image',
            field=models.ImageField(blank=True, help_text='Fallback cover shown on the storefront when a product has no image of its own.', null=True, upload_to='store/'),
        ),
    ]
