# Generated by Django 6.0.5 on 2026-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_storesettings_product_placeholder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(default='', editable=False, help_text='First chars, for identification.', max_length=16),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
