# Generated by Django 6.0.5 on 2026-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_apikey_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='guided_ux_mode',
            field=models.BooleanField(default=True, help_text='Enable enhanced micro-animations and highly visible contextual explanations across the dashboard.'),
        ),
    ]
