# Generated by Django 6.0.5 on 2026-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_storesettings_guided_ux_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='guided_ux_mode',
        ),
        migrations.AddField(
            model_name='storesettings',
            name='ai_page_help',
            field=models.BooleanField(
                default=False,
                help_text='Show Linda on every dashboard page to explain what you are looking at and advise what to do. Uses your configured AI provider.',
            ),
        ),
    ]
