# Generated by Django 6.0.5 on 2026-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_storesettings_guided_ux_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='core_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
