# Generated by Django 6.0.5 on 2026-07-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_storesettings_core_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
