# Generated by Django 6.0.5 on 2026-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_outboxevent_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gdpr_enabled',
            field=models.BooleanField(default=True, help_text='Show GDPR/ePrivacy features: cookie-consent banner and self-service data export + account deletion. Turn off for stores outside GDPR jurisdiction.'),
        ),
    ]
