# Generated by Django 6.0.5 on 2026-07-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_storesettings_gdpr_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='ai_daily_briefing',
            field=models.BooleanField(default=False, help_text='Every morning Linda reviews the last 24 hours (sales, errors, stock, reviews) and posts a briefing with suggested actions on the dashboard home. Uses your configured AI provider.'),
        ),
    ]
