# Generated by Django 6.0.5 on 2026-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storesettings_ai_daily_briefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='default_from_email',
            field=models.CharField(blank=True, help_text='e.g. noreply@example.com', max_length=200),
        ),
    ]
