# Generated by Django 6.0.5 on 2026-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_store_settings_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='default_social_image',
            field=models.ImageField(blank=True, help_text='Default social/share (Open Graph) image used when a page has no image of its own. 1200×630 recommended. A per-page or SEO URL override still wins.', null=True, upload_to='store/'),
        ),
    ]
