# Generated by Django 6.0.5 on 2026-07-20 23:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_storesettings_default_social_image'),
        # Fresh-DB ordering: agent_core's history CREATES the tables this
        # state-only migration maps onto.
        ('agent_core', '0003_agentapprovalrequest_args_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # State-only: the tables/indexes already exist under their original
        # agent_core_* names (db_table pins them) — zero SQL (ADR 0034).
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.CreateModel(
                name='AgentRun',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('agent_name', models.CharField(db_index=True, max_length=100)),
                    ('audience', models.CharField(choices=[('storefront', 'Storefront'), ('merchant', 'Merchant'), ('system', 'System'), ('any', 'Any')], default='merchant', max_length=20)),
                    ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                    ('user_message', models.TextField()),
                    ('final_text', models.TextField(blank=True)),
                    ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                    ('error', models.TextField(blank=True)),
                    ('metadata', models.JSONField(blank=True, default=dict)),
                    ('provider', models.CharField(blank=True, max_length=50)),
                    ('model', models.CharField(blank=True, max_length=100)),
                    ('prompt_tokens', models.PositiveIntegerField(default=0)),
                    ('completion_tokens', models.PositiveIntegerField(default=0)),
                    ('tool_call_count', models.PositiveIntegerField(default=0)),
                    ('duration_ms', models.PositiveIntegerField(default=0)),
                    ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                    ('ended_at', models.DateTimeField(blank=True, null=True)),
                    ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'agent_core_agentrun',
                    'ordering': ['-started_at'],
                },
            ),
            migrations.CreateModel(
                name='AgentApprovalRequest',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('tool_name', models.CharField(max_length=200)),
                    ('arguments', models.JSONField(default=dict)),
                    ('args_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                    ('consumed_at', models.DateTimeField(blank=True, null=True)),
                    ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                    ('note', models.TextField(blank=True)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('decided_at', models.DateTimeField(blank=True, null=True)),
                    ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.agentrun')),
                ],
                options={
                    'db_table': 'agent_core_agentapprovalrequest',
                    'ordering': ['-created_at'],
                },
            ),
            migrations.CreateModel(
                name='AgentStep',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('seq', models.PositiveIntegerField()),
                    ('kind', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('final', 'Final answer'), ('error', 'Error')], db_index=True, max_length=20)),
                    ('name', models.CharField(blank=True, help_text='Tool name, when applicable', max_length=200)),
                    ('content', models.TextField(blank=True)),
                    ('arguments', models.JSONField(blank=True, default=dict)),
                    ('output', models.JSONField(blank=True, default=dict)),
                    ('metadata', models.JSONField(blank=True, default=dict)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.agentrun')),
                ],
                options={
                    'db_table': 'agent_core_agentstep',
                    'ordering': ['run', 'seq'],
                },
            ),
            migrations.AddIndex(
                model_name='agentrun',
                index=models.Index(fields=['agent_name', '-started_at'], name='agent_core__agent_n_9ce769_idx'),
            ),
            migrations.AddIndex(
                model_name='agentrun',
                index=models.Index(fields=['customer', '-started_at'], name='agent_core__custome_1f3518_idx'),
            ),
            migrations.AddIndex(
                model_name='agentstep',
                index=models.Index(fields=['run', 'seq'], name='agent_core__run_id_9794a6_idx'),
            ),
            ],
            database_operations=[],
        ),
    ]
