# Generated by Django 6.0.5 on 2026-09-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_agentrun_agentapprovalrequest_agentstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='permalink_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
