# Generated by Django 6.0.4 on 2026-04-24 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('preview', 'Preview / PR')], db_index=True, default='development', max_length=15)),
                ('is_protected', models.BooleanField(default=False, help_text='Mutations require an explicit confirm flag (typically true for production).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('settings_overrides', models.JSONField(blank=True, default=dict)),
                ('theme_overrides', models.JSONField(blank=True, default=dict)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='environments.environment')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='environments.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='environments.environment')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environmentsnapshot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['kind', 'is_active'], name='environment_kind_d34858_idx'),
        ),
    ]
