# Generated by Django 6.0.4 on 2026-04-24 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(blank=True, max_length=200)),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('constraint', 'Constraint'), ('context', 'Life Context'), ('relationship', 'Relationship'), ('feedback', 'Feedback'), ('behavior', 'Observed Behavior')], max_length=15)),
                ('key', models.CharField(max_length=200)),
                ('value', models.JSONField()),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('explicit', 'Customer Stated'), ('inferred', 'Inferred from Behavior'), ('agent', 'Set by AI Agent'), ('purchase', 'Derived from Purchase')], max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=200, unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_browse', models.BooleanField(default=True)),
                ('can_purchase', models.BooleanField(default=False)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('budget_limit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_limit_currency', models.CharField(default='USD', max_length=3)),
                ('allowed_categories', models.JSONField(default=list)),
                ('purchase_requires_approval', models.BooleanField(default=True)),
                ('total_spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('metric', models.CharField(choices=[('conversion_rate', 'Conversion Rate'), ('click_through', 'Click-Through Rate'), ('cart_add', 'Add-to-Cart Rate'), ('revenue_per_session', 'Revenue Per Session'), ('chat_satisfaction', 'Chat Satisfaction Score')], max_length=25)),
                ('traffic_split', models.FloatField(default=0.5)),
                ('status', models.CharField(choices=[('running', 'Running'), ('concluded', 'Concluded'), ('paused', 'Paused')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('completion', 'Text Completion'), ('embedding', 'Embedding'), ('intent_parse', 'Intent Parsing'), ('product_description', 'Product Description'), ('recommendation', 'Recommendation'), ('chat', 'Customer Chat'), ('zero_shot', 'Zero-Shot Catalog'), ('merchant_insight', 'Merchant Insight'), ('dynamic_pricing', 'Dynamic Pricing'), ('synthetic_test', 'Synthetic Test')], max_length=30)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('agent_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('predicted_units', models.IntegerField()),
                ('confidence_low', models.IntegerField()),
                ('confidence_high', models.IntegerField()),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='MerchantInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('opportunity', 'Revenue Opportunity'), ('risk', 'Risk / Alert'), ('action', 'Suggested Action'), ('report', 'Automated Report')], max_length=15)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('suggested_action', models.JSONField(default=dict)),
                ('estimated_impact', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(null=True)),
                ('ai_executed', models.BooleanField(default=False)),
                ('execution_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prompt_type', models.CharField(choices=[('product_description', 'Product Description Generator'), ('intent_parser', 'Intent Parser'), ('semantic_search', 'Semantic Search Rewriter'), ('cart_recovery', 'Cart Recovery Message'), ('zero_shot_catalog', 'Zero-Shot Catalog'), ('recommendation', 'Recommendation Explanation'), ('merchant_insight', 'Merchant Insight Generator'), ('chat_response', 'Customer Chat Response'), ('dynamic_pricing', 'Dynamic Pricing Reasoning')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('template', models.TextField(help_text='Jinja2 template with {{variables}}')),
                ('system_message', models.TextField(blank=True)),
                ('model_override', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
    ]
