# Generated by Django 6.0.4 on 2026-04-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0002_initial'),
        ('catalog', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='catalog.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.prompttemplate'),
        ),
        migrations.AddField(
            model_name='aiexperiment',
            name='prompt_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_a', to='ai_assistant.prompttemplate'),
        ),
        migrations.AddField(
            model_name='aiexperiment',
            name='prompt_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_b', to='ai_assistant.prompttemplate'),
        ),
        migrations.AddField(
            model_name='aiexperiment',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_experiments', to='ai_assistant.prompttemplate'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['customer', 'memory_type'], name='ai_assistan_custome_0865e7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['agent_id'], name='ai_assistan_agent_i_547330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandforecast',
            unique_together={('product_variant', 'forecast_date', 'model_version')},
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='ai_assistan_interac_935aed_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['customer', 'created_at'], name='ai_assistan_custome_81c91d_idx'),
        ),
    ]
