# Generated by Django 6.0.4 on 2026-04-24 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_initial'),
        ('catalog', '0003_product_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('reasoning', models.TextField(blank=True)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_rule', to='catalog.product')),
            ],
        ),
    ]
