# Generated by Django 6.0.5 on 2026-07-15 00:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_agentregistration_signing_secret_agentintent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('ref', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('vector', models.JSONField(default=list)),
                ('dim', models.PositiveIntegerField(default=0)),
                ('source_text_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'ref'],
                'constraints': [models.UniqueConstraint(fields=('source', 'ref'), name='uniq_knowledge_source_ref')],
            },
        ),
    ]
