# Generated by Django 6.0.4 on 2026-04-24 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('installed_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plugin Config',
                'verbose_name_plural': 'Plugin Configs',
                'ordering': ['plugin_name'],
            },
        ),
    ]
