# Generated by Django 6.0.4 on 2026-04-25 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('code', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(help_text='ISO-3166 alpha-2 code, e.g. US', max_length=2)),
                ('region', models.CharField(blank=True, help_text='Subdivision code, e.g. CA, NY', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'region', 'name'],
                'unique_together': {('country', 'region')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g. "VAT 20%")', max_length=120)),
                ('rate_percent', models.DecimalField(decimal_places=3, help_text='Percent — 8.875 means 8.875%', max_digits=6)),
                ('is_compound', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower = applied first; matters when is_compound=True.')),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for the default rate in this region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='tax.taxcategory')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tax.taxregion')),
            ],
            options={
                'ordering': ['region', 'priority', 'category'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('local', 'Local rates'), ('stripe', 'Stripe Tax'), ('none', 'No tax')], default='local', max_length=10)),
                ('prices_include_tax', models.BooleanField(default=False, help_text='If True, product prices already include tax (EU pattern).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_region', models.ForeignKey(blank=True, help_text='Used when no shipping address is available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxregion')),
            ],
        ),
    ]
