# Generated by Django 6.0.5 on 2026-10-06 22:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0017_alter_productvariant_variant_type'),
        ('orders', '0012_order_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendropOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('placed', 'Placed in Zendrop'), ('shipped', 'Shipped (tracking recorded)'), ('cancelled', 'Cancelled after placing — cancel in Zendrop too')], default='placed', max_length=20)),
                ('zendrop_order_number', models.CharField(blank=True, max_length=100)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zendrop_order', to='orders.order')),
            ],
            options={
                'ordering': ['-placed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZendropLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zendrop_product_id', models.CharField(blank=True, max_length=64)),
                ('zendrop_variant_id', models.CharField(blank=True, max_length=64)),
                ('product_url', models.URLField(blank=True, help_text='Zendrop product page', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zendrop_links', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zendrop_links', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['product__name', 'variant__sku'],
                'unique_together': {('product', 'variant')},
            },
        ),
    ]
