# Generated by Django 6.0.5 on 2026-06-14 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStoryBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the heading.', max_length=60)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, help_text='Optional image URL.', max_length=500)),
                ('layout', models.CharField(choices=[('image_right', 'Image right'), ('image_left', 'Image left'), ('image_full', 'Full-width image'), ('text', 'Text only')], default='image_right', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_blocks', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'is_active', 'order'], name='product_sto_product_ec521e_idx')],
            },
        ),
    ]
