# Generated by Django 6.0.5 on 2026-08-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0017_alter_productvariant_variant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='curated_in_rails', to='catalog.product')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
