# Generated by Django 6.0.5 on 2026-06-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='member_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percent off the cart for active subscribers on this plan (0–100).'),
        ),
    ]
