# Generated by Django 6.0.5 on 2026-07-16 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_productvariant_variant_type'),
        ('orders', '0011_order_payment_gateway'),
        ('subscriptions', '0002_plan_member_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cadence_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='kind',
            field=models.CharField(choices=[('plan', 'Plan (billing only)'), ('replenish', 'Replenish'), ('curated', 'Curated box')], default='plan', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_ship_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('skipped', 'Skipped'), ('swapped', 'Swapped'), ('cancelled', 'Cancelled')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='subscriptions.subscription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ship_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('skipped', 'Skipped')], default='scheduled', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['ship_at'],
            },
        ),
    ]
