# Generated by Django 6.0.5 on 2026-05-26 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_productvariant_description_and_more'),
        ('orders', '0009_cart_gift_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookvaultOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bv_ref', models.CharField(blank=True, default='', max_length=64)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookvault_link', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='BookvaultProductLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('is_linked', models.BooleanField(default=False, help_text='True once BV has matched this product to a BV title.')),
                ('bv_title_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookvault_links', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookvault_links', to='catalog.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'is_linked'], name='bookvault_b_product_b8fd4e_idx')],
                'unique_together': {('product', 'variant')},
            },
        ),
    ]
