# Generated by Django 6.0.5 on 2026-05-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_remove_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('panels', models.JSONField(blank=True, default=list)),
                ('poster_portrait_url', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_story', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Web Story',
                'verbose_name_plural': 'Web Stories',
            },
        ),
    ]
