"""Built-in event names.

Re-export of `core.hooks.MorpheusEvents`'s constants as module-level
names so plugin code reads naturally::

    from morpheus import events
    self.register_hook(events.ORDER_PLACED, self.on_order)
"""

from __future__ import annotations

from core.hooks import MorpheusEvents as _E

# Orders
ORDER_PLACED = _E.ORDER_PLACED
ORDER_CONFIRMED = _E.ORDER_CONFIRMED
ORDER_PAID = _E.ORDER_PAID
ORDER_CANCELLED = _E.ORDER_CANCELLED
ORDER_FULFILLED = _E.ORDER_FULFILLED

# Payments
PAYMENT_CAPTURED = _E.PAYMENT_CAPTURED
PAYMENT_FAILED = _E.PAYMENT_FAILED
PAYMENT_REFUNDED = _E.PAYMENT_REFUNDED

# Cart
CART_CREATED = _E.CART_CREATED
CART_UPDATED = _E.CART_UPDATED
CART_ABANDONED = _E.CART_ABANDONED
ADD_TO_CART = _E.ADD_TO_CART
REMOVE_FROM_CART = _E.REMOVE_FROM_CART
BEGIN_CHECKOUT = _E.BEGIN_CHECKOUT

# Filters
CART_CALCULATE_TOTAL = _E.CART_CALCULATE_TOTAL
CART_CALCULATE_BREAKDOWN = _E.CART_CALCULATE_BREAKDOWN
PRODUCT_CALCULATE_PRICE = _E.PRODUCT_CALCULATE_PRICE
ACCOUNT_SUMMARY_FIELDS = _E.ACCOUNT_SUMMARY_FIELDS

# Catalog
PRODUCT_VIEWED = _E.PRODUCT_VIEWED
PRODUCT_CREATED = _E.PRODUCT_CREATED
PRODUCT_UPDATED = _E.PRODUCT_UPDATED
CATEGORY_UPDATED = _E.CATEGORY_UPDATED

# Customers
CUSTOMER_REGISTERED = _E.CUSTOMER_REGISTERED
CUSTOMER_LOGIN = _E.CUSTOMER_LOGIN

# Inventory
PRODUCT_LOW_STOCK = _E.PRODUCT_LOW_STOCK
PRODUCT_OUT_OF_STOCK = _E.PRODUCT_OUT_OF_STOCK

# Search
SEARCH_PERFORMED = _E.SEARCH_PERFORMED

# AI
AI_DESCRIPTION_GENERATED = _E.AI_DESCRIPTION_GENERATED
AI_RECOMMENDATION_REQUESTED = _E.AI_RECOMMENDATION_REQUESTED

# Agent intents
AGENT_INTENT_PROPOSED = _E.AGENT_INTENT_PROPOSED
AGENT_INTENT_AUTHORIZED = _E.AGENT_INTENT_AUTHORIZED
AGENT_INTENT_REJECTED = _E.AGENT_INTENT_REJECTED
AGENT_INTENT_COMPLETED = _E.AGENT_INTENT_COMPLETED
AGENT_INTENT_FAILED = _E.AGENT_INTENT_FAILED

# CMS
CMS_FORM_SUBMITTED = _E.CMS_FORM_SUBMITTED
