# Generated by Django 6.0.4 on 2026-04-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storechannel'),
        ('orders', '0002_order_payment_status_alter_order_status_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.storechannel'),
        ),
    ]
