# Generated by Django 6.0.4 on 2026-04-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
