# Generated by Django 6.0.5 on 2026-05-05 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_storecredit_storecredittxn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Must be at least 1; UI sends a delete instead when reaching 0.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
