# Generated by Django 6.0.5 on 2026-05-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0001_initial'),
        ('orders', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gift_card',
            field=models.ForeignKey(blank=True, help_text='Customer-applied gift card; redeemed against the cart at order time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gift_cards.giftcard'),
        ),
    ]
