# Generated by Django 6.0.5 on 2026-05-30 03:42
# Hand-edited to backfill the unique callable default for existing rows
# before applying the unique constraint.

import plugins.installed.orders.models
from django.db import migrations, models


def _backfill_public_tokens(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    from plugins.installed.orders.models import _gen_public_token
    # AddField already populates with the default; re-run to cover any
    # rows that ended up blank (some backends won't call the default for
    # existing rows in older Django releases).
    for pk in Order.objects.filter(public_token__in=['', None]).values_list('pk', flat=True):
        Order.objects.filter(pk=pk).update(public_token=_gen_public_token())


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart_gift_card'),
    ]

    operations = [
        # Step 1: add the column without the unique constraint so the
        # callable default can populate distinct values per row.
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.CharField(
                default=plugins.installed.orders.models._gen_public_token,
                editable=False,
                max_length=43,
            ),
        ),
        # Step 2: backfill any blank values left behind.
        migrations.RunPython(_backfill_public_tokens, _noop_reverse),
        # Step 3: enforce uniqueness once every row has a value.
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.CharField(
                default=plugins.installed.orders.models._gen_public_token,
                editable=False,
                max_length=43,
                unique=True,
            ),
        ),
    ]
