# Generated by Django 6.0.5 on 2026-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
