# Generated by Django 6.0.5 on 2026-10-06 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0017_alter_productvariant_variant_type'),
        ('orders', '0012_order_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('exported', 'Exported to DSers'), ('shipped', 'Shipped (tracking imported)'), ('cancelled', 'Cancelled after export — cancel in DSers too')], default='exported', max_length=20)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_order_number', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_sync', to='orders.order')),
            ],
            options={
                'ordering': ['-exported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_url', models.URLField(blank=True, help_text='AliExpress product URL', max_length=500)),
                ('supplier_sku', models.CharField(blank=True, help_text="The supplier's SKU/variant id as DSers shows it", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsers_links', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsers_links', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['product__name', 'variant__sku'],
                'unique_together': {('product', 'variant')},
            },
        ),
    ]
