# Generated by Django 6.0.5 on 2026-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='workflows_w_workflo_b50f62_idx',
            old_name='workflows_w_workflo_e9c1f5_idx',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='actions',
            field=models.JSONField(blank=True, default=list, help_text='List of {kind, ...kwargs} dicts. See engine.ACTION_HANDLERS.'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='condition',
            field=models.JSONField(blank=True, default=dict, help_text='Optional condition AST. Supported operators: `{"all": [...]}`, `{"any": [...]}`, `{"not": ...}`, `{"==": ["path.to.value", "expected"]}`, `{">": ["path", 100]}`, `{"in": ["needle", "haystack"]}`. Empty dict = run every time.'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='actions_taken',
            field=models.JSONField(blank=True, default=list, help_text='Per-action {kind, ok, message}.'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the event payload at fire time.'),
        ),
    ]
