# Generated by Django 6.0.5 on 2026-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_rename_workflows_w_workflo_e9c1f5_idx_workflows_w_workflo_b50f62_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='trigger',
            field=models.CharField(choices=[('order.placed', 'Order placed'), ('order.paid', 'Order paid'), ('order.fulfilled', 'Order fulfilled'), ('order.cancelled', 'Order cancelled'), ('return.requested', 'Return requested'), ('return.refunded', 'Return refunded'), ('product.low_stock', 'Product low stock'), ('product.out_of_stock', 'Product out of stock'), ('customer.registered', 'Customer registered'), ('cart.abandoned', 'Cart abandoned'), ('agent.run.failed', 'Agent run failed'), ('inventory.overstock_detected', 'Inventory overstock detected')], db_index=True, help_text='Event that fires this workflow.', max_length=80),
        ),
    ]
