apiVersion: v1
kind: ConfigMap
metadata:
  name: morpheus-config
  namespace: morpheus
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "morpheus.example.com"
  REDIS_URL: "redis://redis:6379/0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"

