apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: morpheus
  namespace: morpheus
spec:
  rules:
    - host: morpheus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: morpheus-web
                port:
                  number: 80

