"""Seed the 8 launch Montenegro experiences (idempotent).

Ports the real catalogue from the reference montenegro-experience-hub site:
hosts (vendors), categories, regions, locations, prices (+ was-price), ratings,
bestseller flags, highlights, what's included, and the bundled images under
seed_assets/. Safe to re-run — keyed by slug, only creates what's missing.

    python manage.py seed_experiences

Auto-runs on deploy when SEED_EXPERIENCES=1 (see docker-entrypoint.sh).
"""

from __future__ import annotations

from pathlib import Path

from django.core.files import File
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from djmoney.money import Money

SEED_DIR = Path(__file__).resolve().parents[2] / 'seed_assets'

EXPERIENCES = [
    {
        'slug': 'sea-kayaking-adventure-kotor',
        'name': 'Sea Kayaking Adventure in the Bay of Kotor',
        'host': 'Kotor Adventures',
        'category': 'Adventure',
        'region': 'kotor',
        'location': 'Kotor',
        'image': 'kayak.jpg',
        'price': 65,
        'original_price': 85,
        'minutes': 240,
        'duration': '4 hours',
        'cap': 12,
        'party': 10,
        'rating': 4.9,
        'reviews': 234,
        'bestseller': True,
        'short': 'Explore the Bay of Kotor by kayak — hidden caves, secluded swims, dramatic mountains.',
        'description': 'Explore the stunning Bay of Kotor from a unique perspective on this guided sea kayaking adventure. Paddle through crystal-clear waters, discover hidden caves, and swim in secluded spots while surrounded by dramatic mountain scenery.',
        'highlights': [
            'Paddle through UNESCO World Heritage waters',
            'Visit hidden caves and secret beaches',
            'Professional guide with local knowledge',
            'Small groups for a personalised experience',
            'All equipment provided',
        ],
        'included': [
            'Professional guide',
            'Kayak & paddle',
            'Life jacket',
            'Waterproof bag',
            'Light snacks & water',
            'Photos of your adventure',
        ],
        'not_included': ['Hotel pickup', 'Gratuities', 'Personal expenses'],
    },
    {
        'slug': 'luxury-spa-day-adriatic-views-budva',
        'name': 'Luxury Spa Day with Adriatic Views',
        'host': 'Adriatic Wellness',
        'category': 'Wellness',
        'region': 'budva',
        'location': 'Budva',
        'image': 'spa.jpg',
        'price': 120,
        'original_price': None,
        'minutes': 480,
        'duration': 'Full day',
        'cap': 8,
        'party': 6,
        'rating': 4.8,
        'reviews': 156,
        'bestseller': False,
        'short': 'A full day of premium treatments, thermal baths and gourmet cuisine overlooking the Adriatic.',
        'description': 'Indulge in the ultimate relaxation experience at a world-class spa overlooking the Adriatic Sea. Enjoy premium treatments, thermal baths, and gourmet cuisine in a serene setting.',
        'highlights': [
            'Full access to thermal spa facilities',
            '60-minute signature massage',
            'Gourmet lunch included',
            'Stunning sea views',
            'Access to infinity pool',
        ],
        'included': [
            'Spa access (full day)',
            '60-min massage',
            'Lunch',
            'Robe & slippers',
            'Towels',
            'Locker',
        ],
        'not_included': ['Additional treatments', 'Transportation', 'Gratuities'],
    },
    {
        'slug': 'sunset-dining-experience-perast',
        'name': 'Sunset Dining Experience by the Sea',
        'host': 'Perast Fine Dining',
        'category': 'Dining',
        'region': 'kotor',
        'location': 'Perast',
        'image': 'dining.jpg',
        'price': 95,
        'original_price': 120,
        'minutes': 180,
        'duration': '3 hours',
        'cap': 20,
        'party': 8,
        'rating': 4.9,
        'reviews': 312,
        'bestseller': True,
        'short': 'A 5-course Montenegrin tasting menu with wine pairing as the sun sets over the Bay of Kotor.',
        'description': 'Experience an unforgettable evening of fine Montenegrin cuisine as the sun sets over the Bay of Kotor. Savor a carefully curated 5-course meal paired with local wines at a historic waterfront restaurant.',
        'highlights': [
            '5-course tasting menu',
            'Premium wine pairing',
            'Waterfront seating',
            'Live traditional music',
            'Stunning sunset views',
        ],
        'included': [
            '5-course meal',
            'Wine pairing (4 glasses)',
            'Welcome drink',
            'Coffee & petit fours',
            'Waterfront table',
        ],
        'not_included': ['Transportation', 'Additional drinks', 'Gratuities'],
    },
    {
        'slug': 'durmitor-national-park-hiking-zabljak',
        'name': 'Durmitor National Park Hiking',
        'host': 'Mountain Explorers',
        'category': 'Adventure',
        'region': 'durmitor',
        'location': 'Žabljak',
        'image': 'hiking.jpg',
        'price': 75,
        'original_price': None,
        'minutes': 480,
        'duration': '8 hours',
        'cap': 12,
        'party': 10,
        'rating': 4.7,
        'reviews': 189,
        'bestseller': False,
        'short': 'A guided trek through Durmitor — glacial lakes, alpine scenery and a traditional mountain lunch.',
        'description': 'Discover the breathtaking beauty of Durmitor National Park on this guided hiking adventure. Trek through pristine wilderness, past glacial lakes, and enjoy panoramic mountain views.',
        'highlights': [
            'UNESCO World Heritage Site',
            'Experienced mountain guide',
            'Visit Black Lake',
            'Stunning alpine scenery',
            'Traditional lunch included',
        ],
        'included': [
            'Professional guide',
            'Park entrance fee',
            'Traditional lunch',
            'Hiking poles',
            'First aid kit',
        ],
        'not_included': ['Transportation to Žabljak', 'Personal hiking gear', 'Travel insurance'],
    },
    {
        'slug': 'private-yacht-charter-tivat',
        'name': 'Private Yacht Charter',
        'host': 'Porto Montenegro Yachts',
        'category': 'Water Sports',
        'region': 'tivat',
        'location': 'Tivat',
        'image': 'sailing.jpg',
        'price': 350,
        'original_price': 450,
        'minutes': 360,
        'duration': '6 hours',
        'cap': 8,
        'party': 8,
        'rating': 5.0,
        'reviews': 87,
        'bestseller': True,
        'short': 'Cruise the Montenegrin coast on a private yacht with captain, champagne and secluded swim stops.',
        'description': 'Experience the Montenegrin coast in style aboard a private yacht. Cruise along the stunning coastline, anchor at secluded bays, and enjoy premium refreshments while your captain takes care of everything.',
        'highlights': [
            'Private yacht with captain',
            'Champagne & canapés included',
            'Swim stops at hidden bays',
            'Snorkeling equipment',
            'Fully customisable itinerary',
        ],
        'included': [
            'Private yacht (6 hours)',
            'Captain & crew',
            'Champagne',
            'Canapés & fruit',
            'Snorkeling gear',
            'Towels',
        ],
        'not_included': ['Fuel surcharge (if applicable)', 'Lunch (can be arranged)', 'Gratuities'],
    },
    {
        'slug': 'old-town-walking-tour-kotor',
        'name': 'Old Town Walking Tour',
        'host': 'Kotor History Tours',
        'category': 'Culture',
        'region': 'kotor',
        'location': 'Kotor',
        'image': 'culture.jpg',
        'price': 35,
        'original_price': None,
        'minutes': 150,
        'duration': '2.5 hours',
        'cap': 15,
        'party': 10,
        'rating': 4.8,
        'reviews': 456,
        'bestseller': False,
        'short': 'Discover medieval Kotor with a local guide — ancient streets, churches and hidden courtyards.',
        'description': "Discover the rich history and hidden gems of Kotor's medieval Old Town with a passionate local guide. Wander through ancient streets, visit historic churches, and hear fascinating stories.",
        'highlights': [
            'UNESCO World Heritage Old Town',
            'Expert local guide',
            'Visit St. Tryphon Cathedral',
            'Hidden courtyards & stories',
            'Small group experience',
        ],
        'included': ['Expert guide', 'Cathedral entrance', 'Welcome drink', 'Map & guide book'],
        'not_included': ['Additional entrance fees', 'Food & drinks', 'Gratuities'],
    },
    {
        'slug': 'mountain-wine-tasting-crmnica',
        'name': 'Mountain Wine Tasting',
        'host': 'Montenegro Wine Tours',
        'category': 'Wine',
        'region': 'skadar',
        'location': 'Crmnica',
        'image': 'wine.jpg',
        'price': 55,
        'original_price': None,
        'minutes': 240,
        'duration': '4 hours',
        'cap': 10,
        'party': 10,
        'rating': 4.9,
        'reviews': 123,
        'bestseller': False,
        'short': 'Taste 8+ wines at family-owned vineyards near Lake Skadar, with local cheese and meat boards.',
        'description': 'Journey to the heart of Montenegrin wine country and taste exceptional wines from family-owned vineyards. Learn about traditional winemaking methods and enjoy local delicacies.',
        'highlights': [
            'Visit 2 family wineries',
            'Taste 8+ premium wines',
            'Local cheese & meat board',
            'Meet the winemakers',
            'Stunning vineyard views',
        ],
        'included': [
            'Wine tastings (8+ wines)',
            'Food pairings',
            'Winery tours',
            'Sommelier guide',
            'Bottle of wine to take home',
        ],
        'not_included': ['Transportation', 'Additional wine purchases', 'Gratuities'],
    },
    {
        'slug': 'premium-wellness-retreat-sveti-stefan',
        'name': 'Premium Wellness Retreat',
        'host': 'Aman Wellness',
        'category': 'Wellness',
        'region': 'budva',
        'location': 'Sveti Stefan',
        'image': 'spa.jpg',
        'price': 150,
        'original_price': None,
        'minutes': 480,
        'duration': 'Full day',
        'cap': 8,
        'party': 8,
        'rating': 4.9,
        'reviews': 98,
        'bestseller': False,
        'short': 'A curated wellness day near iconic Sveti Stefan — treatments, yoga and organic cuisine.',
        'description': "Escape to an exclusive wellness sanctuary near the iconic Sveti Stefan. Enjoy a curated program of treatments, yoga, and healthy cuisine in one of Montenegro's most beautiful settings.",
        'highlights': [
            'Exclusive wellness sanctuary',
            'Personalised treatment program',
            'Yoga & meditation sessions',
            'Organic gourmet meals',
            'Views of Sveti Stefan',
        ],
        'included': [
            'Full wellness program',
            '2 spa treatments',
            'Yoga class',
            'Organic lunch & snacks',
            'Use of all facilities',
        ],
        'not_included': ['Transportation', 'Additional treatments', 'Overnight stay'],
    },
    {
        'slug': 'perast-our-lady-of-the-rocks-boat-tour',
        'name': 'Perast & Our Lady of the Rocks Boat Tour',
        'host': 'Bay of Kotor Boats',
        'category': 'Water Sports',
        'region': 'kotor',
        'location': 'Perast',
        'image': 'sailing.jpg',
        'price': 40,
        'original_price': None,
        'minutes': 120,
        'duration': '2 hours',
        'cap': 20,
        'party': 12,
        'rating': 4.8,
        'reviews': 278,
        'bestseller': True,
        'short': 'A short boat trip from Perast to the man-made islet church of Our Lady of the Rocks.',
        'description': 'Glide across the calm waters of the inner Bay of Kotor to the iconic islet of Our Lady of the Rocks. Visit the church and its museum, hear the legend of the sailors who built the island stone by stone, and take in views of baroque Perast.',
        'highlights': [
            'Visit the islet church & museum',
            'The legend of Our Lady of the Rocks',
            'Baroque Perast waterfront',
            'Calm, scenic bay crossing',
            'Great for all ages',
        ],
        'included': ['Return boat transfer', 'Local skipper', 'Church entrance', 'Bottled water'],
        'not_included': ['Museum donation', 'Gratuities', 'Hotel pickup'],
    },
    {
        'slug': 'tara-river-rafting-durmitor',
        'name': 'Tara River Rafting',
        'host': 'Tara Rafting Co',
        'category': 'Adventure',
        'region': 'durmitor',
        'location': 'Tara Canyon',
        'image': 'hiking.jpg',
        'price': 70,
        'original_price': 90,
        'minutes': 300,
        'duration': 'Half day',
        'cap': 24,
        'party': 12,
        'rating': 4.9,
        'reviews': 415,
        'bestseller': True,
        'short': 'Raft the emerald Tara through Europe’s deepest canyon — rapids, cliffs and pristine water.',
        'description': 'Take on the rapids of the Tara River as it carves through the deepest canyon in Europe. With an experienced guide steering each raft, you’ll splash through white water, drift past sheer cliffs, and stop to swim in water clean enough to drink.',
        'highlights': [
            'Europe’s deepest river canyon',
            'Grade II–III rapids (beginner-friendly)',
            'Swim in crystal-clear water',
            'Certified rafting guides',
            'Traditional lunch after the run',
        ],
        'included': [
            'Raft, paddle & helmet',
            'Wetsuit & life jacket',
            'Certified guide',
            'Traditional lunch',
            'Insurance',
        ],
        'not_included': ['Transport to the put-in', 'Towel & swimwear', 'Gratuities'],
    },
    {
        'slug': 'ostrog-monastery-day-trip',
        'name': 'Ostrog Monastery Day Trip',
        'host': 'Montenegro Day Tours',
        'category': 'Culture',
        'region': 'podgorica',
        'location': 'Ostrog',
        'image': 'culture.jpg',
        'price': 45,
        'original_price': None,
        'minutes': 420,
        'duration': '7 hours',
        'cap': 16,
        'party': 12,
        'rating': 4.7,
        'reviews': 203,
        'bestseller': False,
        'short': 'Visit the cliff-carved Ostrog Monastery, Montenegro’s most revered pilgrimage site.',
        'description': 'Journey inland to Ostrog, a white monastery set impossibly into a vertical rock face. A guide shares the story of St. Basil and the pilgrims who come from across the Balkans, with time to visit the upper and lower monasteries and enjoy mountain views.',
        'highlights': [
            'The dramatic cliff-set monastery',
            'Story of St. Basil of Ostrog',
            'Upper & lower monastery visit',
            'Scenic drive through the interior',
            'Small-group comfort',
        ],
        'included': ['Air-conditioned transport', 'Expert guide', 'Bottled water'],
        'not_included': ['Lunch', 'Donations', 'Gratuities'],
    },
    {
        'slug': 'lovcen-njegusi-village-food-tour',
        'name': 'Lovćen & Njeguši Village Food Tour',
        'host': 'Njeguši Tastes',
        'category': 'Dining',
        'region': 'kotor',
        'location': 'Njeguši',
        'image': 'dining.jpg',
        'price': 60,
        'original_price': 75,
        'minutes': 360,
        'duration': '6 hours',
        'cap': 12,
        'party': 8,
        'rating': 4.9,
        'reviews': 167,
        'bestseller': True,
        'short': 'Drive the Lovćen serpentine to Njeguši for pršut, cheese and homemade rakija.',
        'description': 'Climb the famous 25-hairpin road above Kotor to Lovćen National Park and the village of Njeguši, birthplace of the Petrović dynasty. Taste the pršut and cheese the village is famous for, straight from the smokehouse, with local wine and rakija.',
        'highlights': [
            'The Kotor serpentine & viewpoints',
            'Lovćen National Park',
            'Njeguši pršut & cheese tasting',
            'Homemade wine & rakija',
            'Village history',
        ],
        'included': [
            'Transport & driver-guide',
            'Full tasting board',
            'Wine & rakija',
            'Park entrance',
        ],
        'not_included': ['Njegoš Mausoleum ticket', 'Extra purchases', 'Gratuities'],
    },
    {
        'slug': 'lake-skadar-boat-safari',
        'name': 'Lake Skadar Boat Safari',
        'host': 'Skadar Lake Cruises',
        'category': 'Water Sports',
        'region': 'skadar',
        'location': 'Virpazar',
        'image': 'kayak.jpg',
        'price': 30,
        'original_price': None,
        'minutes': 150,
        'duration': '2.5 hours',
        'cap': 20,
        'party': 12,
        'rating': 4.8,
        'reviews': 241,
        'bestseller': False,
        'short': 'Cruise the largest lake in the Balkans — birdlife, water lilies and island monasteries.',
        'description': 'Set off from Virpazar into Lake Skadar National Park, a wetland wonderland of floating water lilies, hidden coves and Dalmatian pelicans. Your skipper points out island monasteries and the best spots for a swim in the warm, shallow water.',
        'highlights': [
            'Largest lake in the Balkans',
            'Pelicans & rich birdlife',
            'Water-lily fields in bloom',
            'Island monasteries',
            'Swim stop in summer',
        ],
        'included': ['Boat cruise', 'Local skipper', 'National park fee', 'Bottled water'],
        'not_included': ['Lunch in Virpazar', 'Gratuities', 'Hotel pickup'],
    },
    {
        'slug': 'budva-old-town-evening-walking-tour',
        'name': 'Budva Old Town Evening Walking Tour',
        'host': 'Budva Walks',
        'category': 'Culture',
        'region': 'budva',
        'location': 'Budva',
        'image': 'culture.jpg',
        'price': 25,
        'original_price': None,
        'minutes': 120,
        'duration': '2 hours',
        'cap': 18,
        'party': 12,
        'rating': 4.6,
        'reviews': 198,
        'bestseller': False,
        'short': 'Walk the walls and lantern-lit lanes of Budva’s old town as the riviera lights up.',
        'description': 'As the day cools, explore the Venetian citadel and marble streets of Budva’s old town. Your guide unpacks 2,500 years of history — Greeks, Romans, Venetians — and points you to the best spots for a nightcap once the tour ends.',
        'highlights': [
            'Venetian citadel & sea walls',
            '2,500 years of history',
            'Lantern-lit marble lanes',
            'Golden-hour photo stops',
            'Local nightlife tips',
        ],
        'included': ['Local guide', 'Citadel entrance', 'Welcome drink'],
        'not_included': ['Food & drinks', 'Gratuities'],
    },
    {
        'slug': 'nevidio-canyon-canyoning',
        'name': 'Canyoning in Nevidio Canyon',
        'host': 'Nevidio Adventures',
        'category': 'Adventure',
        'region': 'durmitor',
        'location': 'Šavnik',
        'image': 'hiking.jpg',
        'price': 85,
        'original_price': None,
        'minutes': 360,
        'duration': '6 hours',
        'cap': 10,
        'party': 8,
        'rating': 4.9,
        'reviews': 132,
        'bestseller': True,
        'short': 'Swim, jump and abseil through the legendary “invisible” canyon of Nevidio.',
        'description': 'Nevidio — “the unseen” — stayed unconquered until 1965. Today, with helmets, wetsuits and expert guides, you can swim its emerald pools, slide its natural chutes and abseil its waterfalls in one of the most thrilling canyoning trips in the Balkans.',
        'highlights': [
            'Legendary Nevidio canyon',
            'Natural slides & jumps',
            'Waterfall abseils',
            'Certified canyoning guides',
            'Small groups only',
        ],
        'included': [
            'Wetsuit, helmet & harness',
            'Certified guides',
            'Safety equipment',
            'Snack & water',
            'Insurance',
        ],
        'not_included': ['Transport to Šavnik', 'Swimwear & shoes', 'Gratuities'],
    },
    {
        'slug': 'paragliding-bay-of-kotor',
        'name': 'Paragliding over the Bay of Kotor',
        'host': 'Adriatic Paragliding',
        'category': 'Adventure',
        'region': 'kotor',
        'location': 'Kotor',
        'image': 'sailing.jpg',
        'price': 110,
        'original_price': None,
        'minutes': 120,
        'duration': '2 hours (incl. transfer)',
        'cap': 6,
        'party': 4,
        'rating': 5.0,
        'reviews': 76,
        'bestseller': True,
        'short': 'A tandem flight from the Vrmac ridge over the fjord-like Bay of Kotor.',
        'description': 'Launch from the Vrmac ridge with a certified tandem pilot and soar over the only fjord-like bay in the Mediterranean. Float above red rooftops, cruise ships and blue water — no experience needed, just show up for the ride of the trip.',
        'highlights': [
            'Tandem flight with a certified pilot',
            'Views over the whole Bay of Kotor',
            'No experience required',
            'Onboard photos & video',
            'Transfer to launch included',
        ],
        'included': [
            'Certified tandem pilot',
            'All flight gear',
            'Transfer to launch',
            'Photos & video',
        ],
        'not_included': ['Gratuities', 'Personal insurance'],
    },
    {
        'slug': 'bar-olive-groves-village-food-tour',
        'name': 'Olive Groves & Village Food Tour near Bar',
        'host': 'Old Olive Tours',
        'category': 'Dining',
        'region': 'ulcinj',
        'location': 'Bar',
        'image': 'dining.jpg',
        'price': 50,
        'original_price': None,
        'minutes': 300,
        'duration': '5 hours',
        'cap': 14,
        'party': 10,
        'rating': 4.7,
        'reviews': 94,
        'bestseller': False,
        'short': 'Meet a thousand-year-old olive tree, press oil and lunch with a local family near Bar.',
        'description': 'The coast around Bar holds some of the oldest olive groves on earth — one tree is over 2,000 years old. Walk the groves, learn how the oil is pressed, and share a long homemade lunch of local specialities with a family who has farmed here for generations.',
        'highlights': [
            'A 2,000-year-old olive tree',
            'Olive oil pressing & tasting',
            'Homemade family lunch',
            'Stari Bar old-town views',
            'Small-group, slow travel',
        ],
        'included': ['Guide & transport', 'Olive oil tasting', 'Full homemade lunch', 'Local wine'],
        'not_included': ['Gratuities', 'Extra purchases'],
    },
    {
        'slug': 'herceg-novi-coastal-walk',
        'name': 'Herceg Novi Coastal Walk & Forte Mare',
        'host': 'Riviera Guides',
        'category': 'Culture',
        'region': 'kotor',
        'location': 'Herceg Novi',
        'image': 'culture.jpg',
        'price': 30,
        'original_price': None,
        'minutes': 150,
        'duration': '2.5 hours',
        'cap': 15,
        'party': 12,
        'rating': 4.6,
        'reviews': 88,
        'bestseller': False,
        'short': 'Climb the “city of stairs” from Forte Mare to hilltop squares and sea-view terraces.',
        'description': 'Herceg Novi tumbles down the hillside at the mouth of the bay in a maze of stairways, forts and flowering terraces. Walk from the seafront Forte Mare up through the old town’s squares and Orthodox churches, with the Adriatic opening up at every turn.',
        'highlights': [
            'Seafront Forte Mare fortress',
            'The famous “city of stairs”',
            'Old-town squares & churches',
            'Panoramic sea terraces',
            'Relaxed local pace',
        ],
        'included': ['Local guide', 'Forte Mare entrance', 'Welcome coffee'],
        'not_included': ['Food & drinks', 'Gratuities'],
    },
    {
        'slug': 'kotor-traditional-cooking-class',
        'name': 'Traditional Montenegrin Cooking Class',
        'host': 'Konoba Kitchen',
        'category': 'Dining',
        'region': 'kotor',
        'location': 'Kotor',
        'image': 'dining.jpg',
        'price': 65,
        'original_price': None,
        'minutes': 210,
        'duration': '3.5 hours',
        'cap': 10,
        'party': 8,
        'rating': 4.9,
        'reviews': 143,
        'bestseller': True,
        'short': 'Cook — and feast on — a Montenegrin menu with a local host near Kotor.',
        'description': 'Roll up your sleeves for a hands-on class in a family konoba. Shop for ingredients, then cook a full Montenegrin menu — from fresh bread and Adriatic seafood to a slow-cooked “ispod sača” — and sit down to enjoy it all with local wine.',
        'highlights': [
            'Hands-on with a local host',
            'Cook a full Montenegrin menu',
            'Learn the “ispod sača” technique',
            'Eat everything you make',
            'Local wine included',
        ],
        'included': [
            'All ingredients',
            'Cooking class',
            'Full meal',
            'Wine & rakija',
            'Recipe cards',
        ],
        'not_included': ['Transport', 'Gratuities'],
    },
    {
        'slug': 'lake-skadar-sunset-wine-cruise',
        'name': 'Lake Skadar Sunset Wine Cruise',
        'host': 'Crmnica Cellars',
        'category': 'Wine',
        'region': 'skadar',
        'location': 'Rijeka Crnojevića',
        'image': 'wine.jpg',
        'price': 55,
        'original_price': 70,
        'minutes': 180,
        'duration': '3 hours',
        'cap': 16,
        'party': 10,
        'rating': 4.8,
        'reviews': 109,
        'bestseller': False,
        'short': 'Sip Crmnica Vranac on a golden-hour cruise from Rijeka Crnojevića.',
        'description': 'Board a wooden boat at the picture-perfect river bend of Rijeka Crnojevića and drift out onto Lake Skadar as the sun drops. Taste Vranac and Krštač from the surrounding Crmnica wine region, paired with local cheese and smoked fish.',
        'highlights': [
            'Golden-hour lake cruise',
            'Crmnica Vranac & Krštač tasting',
            'Local cheese & smoked-fish board',
            'Iconic Rijeka Crnojevića bend',
            'Relaxed, romantic pace',
        ],
        'included': [
            'Sunset boat cruise',
            'Wine tasting (4+ wines)',
            'Cheese & fish board',
            'Skipper & host',
        ],
        'not_included': ['Transport to the dock', 'Extra bottles', 'Gratuities'],
    },
]


DEFAULT_FAQS = [
    {
        'q': 'What if weather conditions are bad?',
        'a': "If conditions make the experience unsafe, we'll offer a full refund or the option to reschedule at no extra cost. We notify you at least 12 hours before the start time.",
    },
    {
        'q': 'Can I bring children?',
        'a': 'Most experiences welcome families — check the group size and any notes on this page, or message the host with your party details.',
    },
    {
        'q': 'What should I wear?',
        'a': 'Comfortable clothing appropriate for the weather and activity, plus sturdy footwear. The host shares any specifics after booking.',
    },
    {
        'q': 'Is transportation included?',
        'a': 'See "What\'s included" above — transport is listed there when provided; otherwise the meeting point is shared after booking.',
    },
]
GALLERY_POOL = [
    'kayak.jpg',
    'sailing.jpg',
    'hiking.jpg',
    'culture.jpg',
    'dining.jpg',
    'spa.jpg',
    'wine.jpg',
]


class Command(BaseCommand):
    help = 'Seed the 8 launch Montenegro experiences (idempotent).'

    def handle(self, *args, **opts):
        from plugins.installed.booking_marketplace.models import BookableService, ServiceImage
        from plugins.installed.catalog.models import Category, Vendor

        created = existing = 0
        for e in EXPERIENCES:
            vendor, _ = Vendor.objects.get_or_create(
                slug=slugify(e['host']), defaults={'name': e['host'], 'is_active': True}
            )
            category, _ = Category.objects.get_or_create(
                slug=slugify(e['category']), defaults={'name': e['category'], 'is_active': True}
            )
            svc, was_created = BookableService.objects.get_or_create(
                slug=e['slug'],
                defaults={
                    'vendor': vendor,
                    'name': e['name'],
                    'category': category,
                    'region': e['region'],
                    'location': e['location'],
                    'short_description': e['short'],
                    'description': e['description'],
                    'price': Money(e['price'], 'EUR'),
                    'original_price': Money(e['original_price'], 'EUR')
                    if e['original_price']
                    else None,
                    'duration_minutes': e['minutes'],
                    'duration_label': e['duration'],
                    'daily_capacity': e['cap'],
                    'max_guests_per_booking': e['party'],
                    'rating': e['rating'],
                    'review_count': e['reviews'],
                    'is_bestseller': e['bestseller'],
                    'highlights': e['highlights'],
                    'included': e['included'],
                    'not_included': e['not_included'],
                    'faqs': e.get('faqs') or DEFAULT_FAQS,
                    'is_active': True,
                },
            )
            if not svc.image:
                src = SEED_DIR / e['image']
                if src.exists():
                    with src.open('rb') as fh:
                        svc.image.save(f'{e["slug"]}.jpg', File(fh), save=True)
            if not svc.faqs:
                svc.faqs = DEFAULT_FAQS
                svc.save(update_fields=['faqs'])
            # Gallery: cover + a few others (idempotent — only when none yet).
            if not svc.images.exists():
                pool = [e['image']] + [g for g in GALLERY_POOL if g != e['image']][:4]
                for i, img in enumerate(pool):
                    src = SEED_DIR / img
                    if src.exists():
                        si = ServiceImage(service=svc, alt=e['name'], sort_order=i)
                        with src.open('rb') as fh:
                            si.image.save(f'{e["slug"]}-{i}.jpg', File(fh), save=True)
            created += was_created
            existing += not was_created
        self.stdout.write(
            self.style.SUCCESS(
                f'Experiences seeded: {created} created, {existing} already present '
                f'({BookableService.objects.count()} total).'
            )
        )
