"""Seed ~100 real Montenegro hotels into the accommodation (stays) engine.

HONESTY NOTE — please read before trusting any field this command writes:

  - Hotel IDENTITY is real: `HOTELS` below lists ~100 real, publicly known
    Montenegro hotels — name, town, region and star class were cross-checked
    against independent booking/review sites before this file was written
    (Regent Porto Montenegro, Aman Sveti Stefan, Hotel Splendid Conference &
    Spa Resort, Palmon Bay, Hotel Podgorica, Chalet Kolašin, One&Only
    Portonovi, and so on are all real, currently operating properties).

  - Everything else is REPRESENTATIVE, not scraped — this command does not
    fetch anything from the hotels themselves. Room names/layouts/occupancy,
    bed configuration, room size, room count, nightly rates, amenity lists,
    rating/review counts, check-in/out times and policies are generated by
    *class* (star rating × property type × region) via `_rooms_for`,
    `_rate_for` and `_amenities_for` below. They are realistic and
    internally consistent so the directory reads well at launch, but they
    are NOT the hotel's actual published rooms, rates or amenities — every
    field is ordinary host-editable data once a vendor claims the listing.

  - Coordinates are the real town/site location (`TOWN_COORDS`) plus a small
    deterministic jitter (~±500 m, seeded by the hotel's slug so it's stable
    across reruns) so hotels sharing a town don't stack on one map pin. They
    are not surveyed exact hotel entrances.

Run:
    python manage.py seed_hotels_montenegro

Idempotent — keyed by `Property.slug`. Re-running only creates what's
missing and only backfills fields that are still empty on an existing row;
it never overwrites data an admin/host may have already edited.
"""

from __future__ import annotations

import hashlib
from datetime import time
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils.text import slugify
from djmoney.money import Money

# ── Real town/site coordinates, mapped to the engine's REGIONS keys ──────────
# (name -> (latitude, longitude, region_key)). Region assignment follows the
# same "which REGIONS bucket does this town read best in" convention already
# used by seed_places.py (e.g. Herceg Novi -> kotor, Bar -> ulcinj).
TOWN_COORDS = {
    'Kotor': (42.4247, 18.7712, 'kotor'),
    'Dobrota': (42.4390, 18.7650, 'kotor'),
    'Prčanj': (42.4667, 18.7167, 'kotor'),
    'Perast': (42.4877, 18.7069, 'kotor'),
    'Herceg Novi': (42.4531, 18.5375, 'kotor'),
    'Igalo': (42.4514, 18.5083, 'kotor'),
    'Meljine': (42.4437, 18.5599, 'kotor'),
    'Kumbor': (42.4363, 18.5697, 'kotor'),
    'Tivat': (42.4356, 18.6997, 'tivat'),
    'Donja Lastva': (42.4276, 18.6889, 'tivat'),
    'Porto Montenegro': (42.4342, 18.6958, 'tivat'),
    'Luštica Bay': (42.4045, 18.6748, 'tivat'),
    'Budva': (42.2911, 18.8400, 'budva'),
    'Bečići': (42.2789, 18.8580, 'budva'),
    'Rafailovići': (42.2825, 18.8499, 'budva'),
    'Pržno': (42.2660, 18.8799, 'budva'),
    'Sveti Stefan': (42.2551, 18.8917, 'budva'),
    'Miločer': (42.2601, 18.8865, 'budva'),
    'Rezevići': (42.2489, 18.9048, 'budva'),
    'Petrovac': (42.2064, 18.9391, 'budva'),
    'Bar': (42.0938, 19.1000, 'ulcinj'),
    'Sutomore': (42.1494, 19.0353, 'ulcinj'),
    'Dobra Voda': (42.1167, 19.0667, 'ulcinj'),
    'Ulcinj': (41.9297, 19.2094, 'ulcinj'),
    'Velika Plaža': (41.8900, 19.2600, 'ulcinj'),
    'Podgorica': (42.4304, 19.2594, 'podgorica'),
    'Žabljak': (43.1547, 19.1223, 'durmitor'),
    'Borje': (43.1350, 19.1050, 'durmitor'),
    'Kolašin': (42.8236, 19.5175, 'durmitor'),
    'Cetinje': (42.3911, 18.9238, 'cetinje'),
    'Virpazar': (42.2564, 19.0947, 'skadar'),
    'Rijeka Crnojevića': (42.3389, 19.0361, 'skadar'),
}

# ── The 100 real hotels: (name, town, star, property_type) ──────────────────
HOTELS = [
    # Kotor / Dobrota / Prčanj
    ('Boutique Hotel Astoria', 'Kotor', 5, 'boutique'),
    ('Historic Boutique Hotel Cattaro', 'Kotor', 4, 'boutique'),
    ('Boutique Hotel Hippocampus', 'Kotor', 4, 'boutique'),
    ('Hotel Villa Duomo', 'Kotor', 4, 'boutique'),
    ('Hotel Monte Cristo', 'Kotor', 3, 'hotel'),
    ('Hotel Vardar', 'Kotor', 3, 'hotel'),
    ('Palazzo Drusko', 'Kotor', 4, 'boutique'),
    ('Casa del Mare', 'Kotor', 4, 'boutique'),
    ('Old Town Hostel Kotor', 'Kotor', 2, 'hostel'),
    ('Hostel Pupa', 'Kotor', 2, 'hostel'),
    ('Forza Mare', 'Dobrota', 5, 'boutique'),
    ('Palazzo Radomiri', 'Dobrota', 4, 'boutique'),
    ('Hotel Forza Terra', 'Dobrota', 4, 'boutique'),
    ('Palazzo Sbutega', 'Prčanj', 4, 'boutique'),
    # Perast
    ('Hotel Conte', 'Perast', 4, 'hotel'),
    ('Heritage Grand Perast', 'Perast', 5, 'boutique'),
    # Herceg Novi / Igalo / Meljine / Kumbor
    ('Lazure Hotel & Marina', 'Herceg Novi', 5, 'boutique'),
    ('Hotel Perla', 'Herceg Novi', 4, 'hotel'),
    ('Palmon Bay Hotel & Spa', 'Igalo', 5, 'resort'),
    ('Hotel Novi', 'Igalo', 3, 'hotel'),
    ('Hotel RR', 'Meljine', 4, 'hotel'),
    ('One&Only Portonovi', 'Kumbor', 5, 'resort'),
    ('Iberostar Selection Kumbor', 'Kumbor', 5, 'resort'),
    ('Carine Hotel Kumbor', 'Kumbor', 4, 'hotel'),
    # Tivat / Porto Montenegro / Luštica Bay / Donja Lastva
    ('Hotel Palma', 'Tivat', 3, 'hotel'),
    ('Boutique Hotel Villa Royal', 'Tivat', 4, 'boutique'),
    ('Carrubba', 'Donja Lastva', 4, 'boutique'),
    ('SeptemberHotels Donja Lastva', 'Donja Lastva', 4, 'boutique'),
    ('Regent Porto Montenegro', 'Porto Montenegro', 5, 'resort'),
    ('Regent Pool Club Villas Porto Montenegro', 'Porto Montenegro', 5, 'villa'),
    ('The Chedi Luštica Bay', 'Luštica Bay', 5, 'resort'),
    # Budva
    ('Avala Resort & Villas', 'Budva', 5, 'resort'),
    ('Hotel Slovenska Plaža', 'Budva', 4, 'resort'),
    ('Hotel Mediteran Budva', 'Budva', 4, 'hotel'),
    ('Hotel Majestic', 'Budva', 4, 'hotel'),
    ('Fontana Hotel & Gastronomy', 'Budva', 4, 'hotel'),
    ('Dukley Hotel & Resort', 'Budva', 5, 'resort'),
    ('Iberostar Slavija', 'Budva', 5, 'hotel'),
    ('Hotel Blue Star', 'Budva', 4, 'hotel'),
    ('Hotel Mogren', 'Budva', 3, 'hotel'),
    # Bečići
    ('Hotel Splendid Conference & Spa Resort', 'Bečići', 5, 'resort'),
    ('Falkensteiner Hotel Montenegro', 'Bečići', 4, 'hotel'),
    ('Iberostar Waves Bellevue', 'Bečići', 4, 'resort'),
    ('U-NIGHT Hostel Budva', 'Bečići', 2, 'hostel'),
    # Rafailovići
    ('Montenegrina Hotel & Spa', 'Rafailovići', 4, 'resort'),
    ('Zeta Hotel', 'Rafailovići', 3, 'hotel'),
    ('Hotel Aleksandar', 'Rafailovići', 3, 'hotel'),
    ('Hotel Meridian', 'Rafailovići', 3, 'hotel'),
    # Pržno / Sveti Stefan / Miločer / Rezevići
    ('Maestral Resort & Casino', 'Pržno', 5, 'resort'),
    ('Aman Sveti Stefan', 'Sveti Stefan', 5, 'resort'),
    ('Villa Milocer', 'Miločer', 5, 'boutique'),
    ('Ananti', 'Rezevići', 5, 'resort'),
    # Petrovac
    ('Hotel Palas', 'Petrovac', 3, 'hotel'),
    ('Hotel Vile Oliva', 'Petrovac', 3, 'hotel'),
    ('Hotel Riviera Petrovac', 'Petrovac', 3, 'hotel'),
    # Bar / Sutomore / Dobra Voda
    ('Kalamper Hotel & Spa', 'Bar', 4, 'resort'),
    ('Iberostar Selection Montenegro', 'Bar', 5, 'resort'),
    ('Hotel Princess', 'Bar', 4, 'hotel'),
    ('Stara Čaršija Hotel & Spa', 'Bar', 4, 'hotel'),
    ('Hotel Del Medio', 'Bar', 3, 'hotel'),
    ('Talički Hill Rustic Villas', 'Bar', 4, 'villa'),
    ('Hotel Porto Sole', 'Sutomore', 3, 'hotel'),
    ('Hotel Sato', 'Sutomore', 3, 'hotel'),
    ('Radisson Resort Ruža Vjetrova', 'Dobra Voda', 5, 'resort'),
    ('Villa Dobre Vode', 'Dobra Voda', 3, 'apartment'),
    # Ulcinj / Velika Plaža
    ('Hotel Mediteran Ulcinj', 'Ulcinj', 4, 'hotel'),
    ('Hotel Albatros', 'Ulcinj', 3, 'hotel'),
    ('Hotel Bellevue', 'Ulcinj', 2, 'hotel'),
    ('Hotel Ambiente Ulcinj', 'Ulcinj', 4, 'hotel'),
    ('iLLYRIA Hotel', 'Ulcinj', 3, 'hotel'),
    ('Azul Beach Resort Montenegro by Karisma', 'Velika Plaža', 4, 'resort'),
    ('Hotel Teuta', 'Velika Plaža', 3, 'hotel'),
    # Podgorica
    ('Hilton Podgorica Crna Gora', 'Podgorica', 5, 'hotel'),
    ('Ramada by Wyndham Podgorica', 'Podgorica', 4, 'hotel'),
    ('Best Western Premier Hotel Montenegro', 'Podgorica', 4, 'hotel'),
    ('Crowne Plaza Podgorica', 'Podgorica', 4, 'hotel'),
    ('Hotel Europa', 'Podgorica', 3, 'hotel'),
    ('Hotel 1920', 'Podgorica', 4, 'hotel'),
    ('Perla Residence Hotel & Spa', 'Podgorica', 4, 'hotel'),
    ('Hotel Laguna', 'Podgorica', 3, 'hotel'),
    ('Bristol Hotel', 'Podgorica', 3, 'hotel'),
    ('voco Podgorica', 'Podgorica', 5, 'hotel'),
    ('Hotel Aurel', 'Podgorica', 4, 'hotel'),
    ('Hotel Podgorica', 'Podgorica', 4, 'hotel'),
    ('City Hotel Podgorica', 'Podgorica', 4, 'hotel'),
    ('Hotel Terminus', 'Podgorica', 3, 'hotel'),
    ('Kings Park Hotel', 'Podgorica', 4, 'hotel'),
    # Žabljak / Borje / Kolašin (Durmitor & the North)
    ('Hotel Žabljak', 'Žabljak', 3, 'hotel'),
    ('Hotel SOA', 'Žabljak', 4, 'mountain_lodge'),
    ('Rezident Hotel', 'Žabljak', 4, 'boutique'),
    ('MB Hotel Žabljak', 'Žabljak', 3, 'guesthouse'),
    ('Hotel Polar Star', 'Borje', 4, 'mountain_lodge'),
    ('Bianca Resort & Spa', 'Kolašin', 4, 'resort'),
    ('Chalet Kolašin', 'Kolašin', 5, 'mountain_lodge'),
    # Cetinje
    ('Grand Hotel Cetinje', 'Cetinje', 3, 'hotel'),
    ('Hotel Monte Rosa', 'Cetinje', 3, 'hotel'),
    ('Hotel Gradska Cetinje', 'Cetinje', 4, 'hotel'),
    # Lake Skadar / Virpazar / Rijeka Crnojevića
    ('Hotel Pelikan', 'Virpazar', 3, 'hotel'),
    ('Villa Miela', 'Virpazar', 3, 'guesthouse'),
    ('Skadar Lake Family Resort', 'Rijeka Crnojevića', 3, 'guesthouse'),
]

# A curated handful of flagship/iconic properties, spread across regions.
FEATURED_NAMES = {
    'Aman Sveti Stefan',
    'Regent Porto Montenegro',
    'One&Only Portonovi',
    'The Chedi Luštica Bay',
    'Villa Milocer',
    'Heritage Grand Perast',
    'Hotel Splendid Conference & Spa Resort',
    'Avala Resort & Villas',
    'Dukley Hotel & Resort',
    'Maestral Resort & Casino',
    'Hilton Podgorica Crna Gora',
    'Hotel Podgorica',
    'Chalet Kolašin',
    'Bianca Resort & Spa',
    'Forza Mare',
}

PTYPE_LABELS = {
    'hotel': 'Hotel',
    'resort': 'Resort',
    'boutique': 'Boutique hotel',
    'apartment': 'Apartment',
    'villa': 'Villa',
    'guesthouse': 'Guesthouse',
    'hostel': 'Hostel',
    'mountain_lodge': 'Mountain lodge',
}

# ── Class-driven room templates (identity ends here; everything below is
# representative, scaled by star rating / property type / region) ──────────
ROOM_TIERS = {
    'default': [
        {
            'name': 'Standard Room',
            'max_adults': 2,
            'max_children': 1,
            'max_occupancy': 3,
            'bed': 'Double or Twin',
            'size': 20,
            'rooms': 14,
            'amenities': ['air_conditioning', 'wifi'],
        },
        {
            'name': 'Deluxe Room',
            'max_adults': 2,
            'max_children': 2,
            'max_occupancy': 4,
            'bed': 'Queen + sofa bed',
            'size': 28,
            'rooms': 10,
            'amenities': ['air_conditioning', 'balcony', 'minibar'],
        },
        {
            'name': 'Junior Suite',
            'max_adults': 2,
            'max_children': 2,
            'max_occupancy': 4,
            'bed': 'King + sofa bed',
            'size': 38,
            'rooms': 6,
            'amenities': ['air_conditioning', 'balcony', 'minibar', 'sea_view'],
        },
        {
            'name': 'Suite',
            'max_adults': 3,
            'max_children': 2,
            'max_occupancy': 5,
            'bed': 'King + separate living area',
            'size': 55,
            'rooms': 4,
            'amenities': ['air_conditioning', 'balcony', 'minibar', 'sea_view', 'bathtub'],
        },
    ],
    'apartment_villa': [
        {
            'name': 'Studio',
            'max_adults': 2,
            'max_children': 1,
            'max_occupancy': 3,
            'bed': 'Double sofa bed',
            'size': 26,
            'rooms': 8,
            'amenities': ['air_conditioning', 'kitchenette', 'wifi'],
        },
        {
            'name': 'One-Bedroom Apartment',
            'max_adults': 2,
            'max_children': 2,
            'max_occupancy': 4,
            'bed': 'Queen + sofa bed',
            'size': 42,
            'rooms': 6,
            'amenities': ['air_conditioning', 'kitchenette', 'balcony'],
        },
        {
            'name': 'Two-Bedroom Apartment',
            'max_adults': 4,
            'max_children': 2,
            'max_occupancy': 6,
            'bed': '2 Queen beds',
            'size': 65,
            'rooms': 4,
            'amenities': ['air_conditioning', 'kitchenette', 'balcony', 'sea_view'],
        },
    ],
    'hostel': [
        {
            'name': 'Dorm Bed (Shared Room)',
            'max_adults': 1,
            'max_children': 0,
            'max_occupancy': 1,
            'bed': 'Bunk bed',
            'size': 4,
            'rooms': 20,
            'amenities': ['wifi'],
        },
        {
            'name': 'Private Room',
            'max_adults': 2,
            'max_children': 1,
            'max_occupancy': 3,
            'bed': 'Double or Twin',
            'size': 14,
            'rooms': 6,
            'amenities': ['wifi', 'air_conditioning'],
        },
    ],
    'mountain_lodge': [
        {
            'name': 'Standard Room',
            'max_adults': 2,
            'max_children': 1,
            'max_occupancy': 3,
            'bed': 'Double or Twin',
            'size': 20,
            'rooms': 10,
            'amenities': ['wifi'],
        },
        {
            'name': 'Chalet Room',
            'max_adults': 2,
            'max_children': 2,
            'max_occupancy': 4,
            'bed': 'Queen + bunk bed',
            'size': 30,
            'rooms': 6,
            'amenities': ['balcony', 'minibar'],
        },
        {
            'name': 'Suite',
            'max_adults': 3,
            'max_children': 2,
            'max_occupancy': 5,
            'bed': 'King + separate living area',
            'size': 45,
            'rooms': 3,
            'amenities': ['balcony', 'minibar', 'bathtub'],
        },
    ],
}

STAR_BASE = {2: 45, 3: 75, 4: 130, 5: 260}
REGION_MULT = {
    'kotor': 1.10,
    'tivat': 1.25,
    'budva': 1.15,
    'ulcinj': 0.95,
    'podgorica': 0.75,
    'durmitor': 0.85,
    'cetinje': 0.80,
    'skadar': 0.85,
    'other': 0.85,
}
PTYPE_MULT = {
    'resort': 1.15,
    'hotel': 1.0,
    'boutique': 1.10,
    'villa': 1.05,
    'apartment': 0.85,
    'guesthouse': 0.70,
    'mountain_lodge': 0.90,
    'hostel': 0.30,
}
TIER_STEP_DEFAULT = Decimal('0.30')
TIER_STEP_HOSTEL = Decimal('1.00')  # a private room ~2x a dorm bed, not +30%/tier

COASTAL_REGIONS = {'kotor', 'budva', 'tivat', 'ulcinj'}


def _stable_hash(key: str) -> int:
    """Deterministic, non-cryptographic hash used only to seed jitter/rating
    generation — never security-sensitive (hence usedforsecurity=False)."""
    return int(hashlib.md5(key.encode(), usedforsecurity=False).hexdigest(), 16)


def _jitter(lat: float, lng: float, key: str, spread: float = 0.008):
    """Deterministic tiny offset (~<=500m) so same-town pins don't stack."""
    h = _stable_hash(key)
    dlat = ((h % 1000) / 1000 - 0.5) * 2 * spread
    dlng = (((h // 1000) % 1000) / 1000 - 0.5) * 2 * spread
    return Decimal(str(round(lat + dlat, 6))), Decimal(str(round(lng + dlng, 6)))


def _rating_and_reviews(key: str, star: int):
    """Deterministic representative rating (~4.0-4.9) and review count."""
    h = _stable_hash(key)
    rating = (Decimal('4.0') + Decimal(h % 10) / Decimal('11')).quantize(Decimal('0.1'))
    review_count = 40 + (h // 10) % 460 + star * 20
    return rating, review_count


def _rate_for(star: int, ptype: str, region: str, tier_index: int) -> Decimal:
    """Representative nightly base rate, scaled by star / property type /
    region / room tier. Not the hotel's actual published rate."""
    base = Decimal(STAR_BASE.get(star, 90))
    mult = Decimal(str(PTYPE_MULT.get(ptype, 1.0))) * Decimal(str(REGION_MULT.get(region, 1.0)))
    step = TIER_STEP_HOSTEL if ptype == 'hostel' else TIER_STEP_DEFAULT
    rate = base * mult * (Decimal('1') + step * tier_index)
    return rate.quantize(Decimal('1'))


def _rooms_for(star: int, ptype: str, region: str):
    """2-4 representative RoomType specs, scaled to class."""
    if ptype in ('apartment', 'villa'):
        pool = ROOM_TIERS['apartment_villa']
    elif ptype == 'hostel':
        pool = ROOM_TIERS['hostel']
    elif ptype == 'mountain_lodge':
        pool = ROOM_TIERS['mountain_lodge']
    else:
        pool = ROOM_TIERS['default']

    n_tiers = min(2 if star <= 3 else (3 if star == 4 else 4), len(pool))
    specs = []
    for i, tier in enumerate(pool[:n_tiers]):
        room_count = max(3, tier['rooms'] - (2 if star < 4 else 0))
        specs.append(
            {
                'name': tier['name'],
                'max_occupancy': tier['max_occupancy'],
                'max_adults': tier['max_adults'],
                'max_children': tier['max_children'],
                'bed_configuration': tier['bed'],
                'size_sqm': tier['size'] + max(0, star - 3) * 3,
                'room_count': room_count,
                'amenities': tier['amenities'],
                'rate': _rate_for(star, ptype, region, i),
            }
        )
    return specs


def _base_amenities(ptype: str):
    """Amenities implied by property type alone, regardless of star/region."""
    a = ['wifi']
    if ptype != 'hostel':
        a.append('parking')
    if ptype in ('hotel', 'resort', 'boutique'):
        a.append('restaurant')
    if ptype == 'mountain_lodge':
        a += ['restaurant', 'bar', 'ev_charging']
    if ptype in ('apartment', 'villa'):
        a += ['kitchenette', 'air_conditioning', 'pet_friendly']
    if ptype == 'guesthouse':
        a += ['family_rooms', 'pet_friendly']
    return a


def _star_amenities(star: int, ptype: str):
    """Amenities implied by star class (higher star -> more facilities)."""
    a = []
    if ptype in ('hotel', 'resort', 'boutique') and star >= 3:
        a.append('bar')
    if star >= 4 and ptype not in ('hostel', 'guesthouse'):
        a += ['air_conditioning', 'pool']
    if star >= 4 and ptype in ('resort', 'boutique', 'hotel'):
        a.append('gym')
    if star >= 4 and ptype in ('resort', 'boutique'):
        a.append('spa')
    if star == 5:
        a += ['concierge', 'room_service']
        if ptype == 'resort':
            a.append('airport_shuttle')
    return a


def _region_amenities(star: int, ptype: str, region: str):
    """Amenities implied by being on the coast (sea view / beachfront)."""
    a = []
    if (
        region in COASTAL_REGIONS
        and star >= 3
        and ptype in ('hotel', 'resort', 'boutique', 'villa')
    ):
        a.append('sea_view')
    if region in COASTAL_REGIONS and ptype == 'resort':
        a.append('beachfront')
    return a


def _amenities_for(star: int, ptype: str, region: str):
    """Representative hotel-level amenity slugs, fitting the class."""
    combined = (
        _base_amenities(ptype)
        + _star_amenities(star, ptype)
        + _region_amenities(star, ptype, region)
    )
    out = []
    for x in combined:
        if x not in out:
            out.append(x)
    return out


def _policies_for(star: int) -> dict:
    return {
        'cancellation': (
            'Free cancellation up to 3 days before check-in.'
            if star >= 4
            else 'Free cancellation up to 24 hours before check-in.'
        ),
        'children': 'Children of all ages are welcome.',
        'pets': 'Pets are not allowed.' if star >= 4 else 'Pets welcome on request.',
        'payment': 'Major credit cards accepted on arrival or online.',
    }


_TIER_WORD = {2: 'a simple, comfortable', 3: 'a well-appointed', 4: 'an upscale', 5: 'a luxury'}

# Guest-salient amenities, most distinguishing first, as noun phrases for the
# meta description. Only amenities the hotel actually has are ever named: a
# description is a public claim, like the rating this store already stopped
# inventing (the aggregateRating landmine) — it must not promise a spa.
_FEATURE_PHRASES = [
    ('sea_view', 'sea views'),
    ('beachfront', 'a beachfront'),
    ('spa', 'a spa'),
    ('pool', 'a pool'),
    ('restaurant', 'a restaurant'),
    ('gym', 'a gym'),
    ('airport_shuttle', 'an airport shuttle'),
    ('wifi', 'free WiFi'),
    ('parking', 'parking'),
]


def _feature_phrase(amenities) -> str:
    """Up to three of the hotel's real, guest-salient amenities, as a phrase
    ('sea views, a spa and a pool'). Empty when it has none worth naming."""
    have = set(amenities or ())
    picked = [phrase for slug, phrase in _FEATURE_PHRASES if slug in have][:3]
    if not picked:
        return ''
    if len(picked) == 1:
        return picked[0]
    return ', '.join(picked[:-1]) + ' and ' + picked[-1]


def _legacy_short_blurb(town: str, star: int, ptype_label: str) -> str:
    """The pre-v0.73.3 short_description — tier + type + town only, which
    collided across every same-class hotel in a town (18 groups / 52 hotels
    live). Kept so `refresh_hotel_blurbs` can tell a platform-generated blurb
    from one a host has since edited, and rewrite only the former — the
    SeoMeta.auto_filled rule (never clobber a human's words)."""
    return f'{_TIER_WORD[star].capitalize()} {ptype_label.lower()} in {town}.'


def _blurb_for(name: str, town: str, star: int, ptype_label: str, amenities):
    """(short_description, description) for one hotel.

    short_description is the hotel page's meta description (stay_views:
    `seo_description`). Leading with the unique hotel name makes all 100
    distinct, and naming real amenities gives each an in-range (70-160 char)
    summary in place of 'An upscale hotel in Podgorica.' on nine hotels at once.
    `description` is the on-page prose and is unchanged."""
    tier_word = _TIER_WORD[star]
    ptype_lower = ptype_label.lower()
    lead = f'{name} is {tier_word} {star}-star {ptype_lower} in {town}, Montenegro'
    feature = _feature_phrase(amenities)
    short = f'{lead}, with {feature}.' if feature else f'{lead}.'
    description = (
        f'{name} is {tier_word} {star}-star {ptype_lower} in {town}, Montenegro, offering '
        f'comfortable rooms for couples, families and small groups, with a range of room types '
        f'to choose from.'
    )
    return short, description


def _field_values(name: str, town: str, star: int, ptype: str) -> dict:
    """Compute every derived Property field for one hotel (pure function)."""
    lat_base, lng_base, region = TOWN_COORDS[town]
    slug = slugify(name)
    lat, lng = _jitter(lat_base, lng_base, slug)
    rating, review_count = _rating_and_reviews(slug, star)
    ptype_label = PTYPE_LABELS.get(ptype, 'Hotel')
    amenities = _amenities_for(star, ptype, region)
    short_desc, desc = _blurb_for(name, town, star, ptype_label, amenities)
    return {
        'slug': slug,
        'name': name,
        'property_type': ptype,
        'star_rating': star,
        'short_description': short_desc,
        'description': desc,
        'region': region,
        'location': town,
        'address': f'{town}, Montenegro',
        'latitude': lat,
        'longitude': lng,
        'amenities': amenities,
        'check_in_time': time(15, 0) if star == 5 else time(14, 0),
        'check_out_time': time(11, 0),
        'policies': _policies_for(star),
        'rating': rating,
        'review_count': review_count,
        'is_featured': name in FEATURED_NAMES,
        'is_active': True,
    }


def _backfill_property(prop, values: dict) -> None:
    """Fill fields still empty on a pre-existing row — never clobber
    something an admin/host may have already edited."""
    is_empty = {
        'short_description': not prop.short_description,
        'description': not prop.description,
        'location': not prop.location,
        'address': not prop.address,
        'latitude': prop.latitude is None,
        'longitude': prop.longitude is None,
        'amenities': not prop.amenities,
        'check_in_time': not prop.check_in_time,
        'check_out_time': not prop.check_out_time,
        'policies': not prop.policies,
        'rating': not prop.rating,
        'review_count': not prop.review_count,
    }
    dirty = [field for field, empty in is_empty.items() if empty]
    for field in dirty:
        setattr(prop, field, values[field])
    if dirty:
        prop.save(update_fields=dirty)


def _create_room_types(prop, star: int, ptype: str, region: str, room_type_model) -> int:
    """Create the class-driven RoomTypes for a brand-new property. No-op if
    the property already has any (never re-seeds/edits existing rooms)."""
    if prop.room_types.exists():
        return 0
    for i, spec in enumerate(_rooms_for(star, ptype, region)):
        room_type_model.objects.create(
            property=prop,
            name=spec['name'],
            slug=slugify(spec['name']),
            max_occupancy=spec['max_occupancy'],
            max_adults=spec['max_adults'],
            max_children=spec['max_children'],
            bed_configuration=spec['bed_configuration'],
            size_sqm=spec['size_sqm'],
            base_rate=Money(spec['rate'], 'EUR'),
            room_count=spec['room_count'],
            amenities=spec['amenities'],
            is_active=True,
            sort_order=i,
        )
    return len(prop.room_types.all())


class Command(BaseCommand):
    help = 'Seed ~100 real Montenegro hotels (representative rooms/rates/amenities). Idempotent.'

    def handle(self, *args, **opts):
        from plugins.installed.booking_marketplace.models import Property, RoomType
        from plugins.installed.catalog.models import Vendor

        hotels_created = hotels_existing = rooms_created = 0

        for name, town, star, ptype in HOTELS:
            values = _field_values(name, town, star, ptype)

            vendor, _ = Vendor.objects.get_or_create(
                slug=values['slug'],
                defaults={
                    'name': name,
                    'description': values['short_description'],
                    'is_active': True,
                },
            )

            defaults = {k: v for k, v in values.items() if k != 'slug'}
            defaults['vendor'] = vendor
            prop, was_created = Property.objects.get_or_create(
                slug=values['slug'], defaults=defaults
            )

            _backfill_property(prop, values)
            rooms_created += _create_room_types(prop, star, ptype, values['region'], RoomType)
            prop.recalc_price_from(save=True)

            hotels_created += was_created
            hotels_existing += not was_created

        self.stdout.write(
            self.style.SUCCESS(
                f'Hotels seeded: {hotels_created} created, {hotels_existing} already present '
                f'({Property.objects.count()} total). Rooms created this run: {rooms_created} '
                f'({RoomType.objects.count()} total).'
            )
        )
