# Generated by Django 6.0.5 on 2026-06-15 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('feed', 'Feed build'), ('catalog_api', 'Catalog API push'), ('capi', 'Conversions API'), ('ads', 'Ads sync')], default='feed', max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('error', 'Error')], default='ok', max_length=10)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='meta_commer_kind_42efe6_idx')],
            },
        ),
    ]
