# Generated by Django 6.0.5 on 2026-08-10 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0017_alter_productvariant_variant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glb_url', models.URLField(blank=True, help_text='.glb for Android Scene Viewer')),
                ('usdz_url', models.URLField(blank=True, help_text='.usdz for iOS Quick Look')),
                ('poster_url', models.URLField(blank=True, help_text='Static poster shown when the device cannot render AR')),
                ('glb_size_bytes', models.PositiveIntegerField(default=0, help_text='Set on upload; reader template fast-fails over the budget')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_3d', to='catalog.product')),
            ],
            options={
                'verbose_name': '3D / AR asset',
                'verbose_name_plural': '3D / AR assets',
            },
        ),
        migrations.CreateModel(
            name='ShoppableVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('markers_json', models.TextField(blank=True, default='[]')),
                ('poster_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppable_videos', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
