# Generated by Django 6.0.4 on 2026-04-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0004_storechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.storechannel'),
        ),
    ]
