# Generated by Django 6.0.4 on 2026-05-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_priceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL. Leave blank to use the default product URL.'),
        ),
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword this product targets — used by SEO audits.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Tell search engines not to follow links from this page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Tell search engines to skip this page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/og/'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra fields merged into the auto-generated JSON-LD (e.g. brand, gtin, mpn).'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with large image')], default='summary_large_image', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/twitter/'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
