# Generated by Django 6.0.4 on 2026-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_canonical_url_product_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='localized_prices',
            field=models.JSONField(blank=True, default=dict, help_text='{"EUR": "19.99", "JPY": "2500"}'),
        ),
        migrations.AddField(
            model_name='product',
            name='localized_translations',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": {"name": "Produit", "description": "..."}}'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='localized_prices',
            field=models.JSONField(blank=True, default=dict, help_text='{"EUR": "19.99", "JPY": "2500"}'),
        ),
    ]
