# Generated by Django 6.0.4 on 2026-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_localized_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/webp/'),
        ),
    ]
