# Generated by Django 6.0.5 on 2026-05-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='UPC / EAN / ISBN. Used by POS, wholesale, and inventory sync.', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Per-variant override of Product.digital_file. Use when a single product sells in multiple digital formats (PDF / EPUB / MOBI).', null=True, upload_to='digital/variants/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='inventory_policy',
            field=models.CharField(choices=[('deny', 'Deny — refuse orders when out of stock'), ('continue', 'Continue — accept backorders')], default='deny', help_text='What happens when stock hits zero. Continue allows backorders.', max_length=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='Per-variant override of Product.is_taxable. Useful for EU VAT where digital + physical have different rules.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='When false, checkout skips the shipping address step. Auto-flipped to false for digital/virtual variants in the dashboard form.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('physical', 'Physical — ships to a customer address'), ('digital', 'Digital — downloadable file'), ('virtual', 'Virtual — service, gift card, booking, no shipment')], default='physical', help_text='Physical (ships), digital (downloadable), or virtual (no fulfillment).', max_length=10),
        ),
    ]
