# Generated by Django 6.0.5 on 2026-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_variant_shopify_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text='Full variant description. Falls back to Product.description when blank.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='short_description',
            field=models.TextField(blank=True, help_text='One-line variant pitch. Falls back to Product.short_description when blank.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Quick free-text size label, e.g. "XL" or "300 ml". For structured size pickers, use attribute_values.', max_length=50),
        ),
    ]
