# Generated by Django 6.0.5 on 2026-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productvariant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='member_products', to='catalog.category'),
        ),
    ]
