# Generated by Django 6.0.5 on 2026-05-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
