# Generated by Django 6.0.5 on 2026-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Extra categories this product is listed under, in addition to its primary category.', related_name='also_listed_products', to='catalog.category'),
        ),
    ]
