# Generated by Django 6.0.5 on 2026-07-12 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(help_text='Display name shown as the page title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shown below the title on the tag page.')),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
