# Generated by Django 6.0.5 on 2026-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_uuidtaggeditem_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('physical', 'Physical — ships to a customer address'), ('digital', 'Digital — downloadable file'), ('audiobook', 'Audiobook — downloadable narration edition'), ('virtual', 'Virtual — service, gift card, booking, no shipment')], default='physical', help_text='Physical (ships), digital (downloadable), or virtual (no fulfillment).', max_length=10),
        ),
    ]
