# Generated by Django 6.0.5 on 2026-07-12 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('export', 'Data export (Art. 15)'), ('erasure', 'Erasure / delete (Art. 17)')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data subject request',
                'verbose_name_plural': 'Data subject requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
