# Generated by Django 6.0.4 on 2026-04-25 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=100)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('episodic', 'Episodic'), ('semantic', 'Semantic')], db_index=True, max_length=10)),
                ('namespace', models.CharField(db_index=True, max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('value', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='agent', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tier', 'namespace'], name='agent_core__tier_312b2d_idx')],
                'unique_together': {('tier', 'namespace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=100)),
                ('audience', models.CharField(choices=[('storefront', 'Storefront'), ('merchant', 'Merchant'), ('system', 'System'), ('any', 'Any')], default='merchant', max_length=20)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_message', models.TextField()),
                ('final_text', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=12)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_core.agentconversation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='agent_core.agentrun')),
            ],
            options={
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=200)),
                ('arguments', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agent_core.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('final', 'Final answer'), ('error', 'Error')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, help_text='Tool name, when applicable', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent_core.agentrun')),
            ],
            options={
                'ordering': ['run', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['agent_name', '-last_message_at'], name='agent_core__agent_n_aceec4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['customer', '-last_message_at'], name='agent_core__custome_720ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['session_key', '-last_message_at'], name='agent_core__session_3f58c9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_name', '-started_at'], name='agent_core__agent_n_9ce769_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['customer', '-started_at'], name='agent_core__custome_1f3518_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'seq'], name='agent_core__run_id_9794a6_idx'),
        ),
    ]
