# Generated by Django 6.0.4 on 2026-04-26 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human label for this background job.', max_length=120)),
                ('agent_name', models.CharField(db_index=True, help_text='Slug of the registered agent to run.', max_length=100)),
                ('prompt', models.TextField(help_text='User-message text passed to the agent on each tick.')),
                ('context_overrides', models.JSONField(blank=True, default=dict)),
                ('interval_seconds', models.PositiveIntegerField(default=3600)),
                ('state', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], db_index=True, default='active', max_length=12)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_id', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('max_failures_before_pause', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['state', 'next_run_at'], name='agent_core__state_832486_idx')],
            },
        ),
    ]
