# Generated by Django 6.0.5 on 2026-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_core', '0002_backgroundagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapprovalrequest',
            name='args_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentapprovalrequest',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
