# Generated by Django 6.0.5 on 2026-07-20 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_core', '0003_agentapprovalrequest_args_fingerprint_and_more'),
        ('assistant', '0013_alter_opsproposal_agent_run'),
        ('core', '0021_agentrun_agentapprovalrequest_agentstep_and_more'),
    ]

    operations = [
        # State-only: the tables/indexes already exist under their original
        # agent_core_* names (db_table pins them) — zero SQL (ADR 0034).
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveField(
                model_name='agentapprovalrequest',
                name='decided_by',
            ),
            migrations.RemoveField(
                model_name='agentapprovalrequest',
                name='run',
            ),
            migrations.RemoveIndex(
                model_name='agentrun',
                name='agent_core__agent_n_9ce769_idx',
            ),
            migrations.RemoveIndex(
                model_name='agentrun',
                name='agent_core__custome_1f3518_idx',
            ),
            migrations.AlterField(
                model_name='agentmessage',
                name='run',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.agentrun'),
            ),
            migrations.RemoveIndex(
                model_name='agentstep',
                name='agent_core__run_id_9794a6_idx',
            ),
            migrations.DeleteModel(
                name='AgentApprovalRequest',
            ),
            migrations.RemoveField(
                model_name='agentstep',
                name='run',
            ),
            migrations.DeleteModel(
                name='AgentRun',
            ),
            migrations.DeleteModel(
                name='AgentStep',
            ),
            ],
            database_operations=[],
        ),
    ]
