# Generated by Django 6.0.5 on 2026-10-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_core', '0004_remove_agentapprovalrequest_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundagent',
            name='daily_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundagent',
            name='engine',
            field=models.CharField(choices=[('linda', 'Linda'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
        migrations.AddField(
            model_name='backgroundagent',
            name='last_output',
            field=models.TextField(blank=True, help_text="The last run's answer (Linda)."),
        ),
    ]
