# Generated by Django 6.0.5 on 2026-05-31 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_order_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('tracking_sent', 'Tracking email sent'), ('delivered_followup', 'Delivered-confirmation follow-up'), ('review_request', 'Review request'), ('nps_survey', 'NPS survey')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='orders.order')),
            ],
            options={
                'verbose_name': 'Journey step',
                'db_table': 'post_purchase_step',
                'ordering': ['-due_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='pp_status_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'step'), name='post_purchase_unique_order_step')],
            },
        ),
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(help_text='0-10')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to='orders.order')),
            ],
            options={
                'verbose_name': 'NPS response',
                'db_table': 'post_purchase_nps',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('order',), name='pp_nps_unique_order'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='pp_nps_score_range')],
            },
        ),
    ]
