# Generated by Django 6.0.5 on 2026-08-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTokenSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('tokens_json', models.TextField(default='{}', help_text='Design tokens: {"colors": {"primary": "#..."}, "fonts": {...}, "spacing": {...}, "radii": {...}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('font', 'Font'), ('icon', 'Icon'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=12)),
                ('url', models.URLField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='brand_kit_a_kind_4069b3_idx')],
            },
        ),
    ]
