# Generated by Django 6.0.5 on 2026-06-12 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
        ('orders', '0011_order_payment_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(choices=[('replenish', 'Replenish'), ('curated', 'Curated')], default='replenish', max_length=10)),
                ('state', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('cadence_days', models.PositiveIntegerField(default=30)),
                ('next_ship_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('skipped', 'Skipped'), ('swapped', 'Swapped'), ('cancelled', 'Cancelled')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('meta_json', models.TextField(blank=True, default='{}')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions_plus.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='subscriptions_plus.subscription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('skipped', 'Skipped')], default='scheduled', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='subscriptions_plus.subscription')),
            ],
            options={
                'ordering': ['ship_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['state', 'next_ship_at'], name='subscriptio_state_a5999b_idx'),
        ),
    ]
