# Generated by Django 6.0.5 on 2026-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='computation',
            field=models.CharField(choices=[('flat', 'Flat fee'), ('weight_tier', 'Weight tiered'), ('order_total_tier', 'Order-total tiered'), ('free_over', 'Free over threshold'), ('carrier_shippo', 'Shippo (live rates)'), ('carrier_easypost', 'EasyPost (live rates)'), ('carrier_bookvault', 'Bookvault (live rates · POD books)')], default='flat', max_length=20),
        ),
    ]
