# Generated by Django 6.0.5 on 2026-05-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='core_auth_e_email_5a40c2_idx',
            old_name='core_auth_e_email_3a1be9_idx',
        ),
    ]
