# Generated by Django 6.0.4 on 2026-04-26 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('catalog', 'Catalog (line-level)'), ('order', 'Order (whole-cart)')], default='order', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first.')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Channel slugs; empty = all channels.')),
                ('requires_coupon', models.CharField(blank=True, help_text='Optional coupon code that unlocks this promotion.', max_length=64)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('predicates', models.JSONField(blank=True, default=dict)),
                ('action', models.JSONField(default=dict)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.promotion')),
            ],
            options={
                'ordering': ['promotion__priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='promotions.promotion')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotionrule')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
