# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productvideo',
            new_name='product_vid_product_7c5752_idx',
            old_name='pv_product_active_sort_idx',
        ),
    ]
