# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morph_errors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorevent',
            new_name='morph_error_fingerp_3c2a2b_idx',
            old_name='err_fp_created_idx',
        ),
        migrations.RenameIndex(
            model_name='errorevent',
            new_name='morph_error_kind_5f567b_idx',
            old_name='err_kind_level_idx',
        ),
    ]
