# Generated by Django 6.0.5 on 2026-05-15 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_id', models.CharField(blank=True, help_text='GA4 stream ID, e.g. G-XXXXXXXXXX', max_length=32)),
                ('api_secret', models.CharField(blank=True, help_text='API secret for the data stream — used by Measurement Protocol.', max_length=120)),
                ('gtm_container_id', models.CharField(blank=True, help_text='GTM web container, e.g. GTM-XXXXXXX', max_length=32)),
                ('sgtm_server_url', models.URLField(blank=True, help_text='Optional server-side GTM endpoint (Cloud Run / Stape).', max_length=500)),
                ('region', models.CharField(choices=[('global', 'Global (www.google-analytics.com)'), ('eu', 'European Union (region1.google-analytics.com)')], default='global', max_length=10)),
                ('server_side_enabled', models.BooleanField(default=True)),
                ('client_side_enabled', models.BooleanField(default=True)),
                ('debug_mode', models.BooleanField(default=False, help_text='Appends ?debug_mode=1 to MP requests — visible in DebugView, not standard reports.')),
                ('event_firing', models.JSONField(blank=True, default=dict, help_text='Per-event enable map, e.g. {"purchase": true, "view_item": true}.')),
                ('enhanced_overrides', models.JSONField(blank=True, default=dict, help_text='Override GA4 Enhanced Measurement defaults.')),
                ('consent_default', models.JSONField(blank=True, default=dict, help_text='Default state per signal — granted/denied per ad_storage, analytics_storage, ad_user_data, ad_personalization.')),
                ('show_consent_banner', models.BooleanField(default=False)),
                ('banner_accept_label', models.CharField(default='Accept all', max_length=40)),
                ('banner_reject_label', models.CharField(default='Reject', max_length=40)),
                ('banner_body', models.CharField(default='We use cookies for analytics and a great shopping experience.', max_length=400)),
                ('banner_link_url', models.CharField(blank=True, max_length=400)),
                ('banner_placement', models.CharField(choices=[('bottom', 'Bottom banner'), ('corner', 'Corner card'), ('modal', 'Blocking modal')], default='bottom', max_length=10)),
                ('user_id_enabled', models.BooleanField(default=False, help_text='Send hashed customer pk as GA4 user_id when authenticated.')),
                ('cross_domain', models.CharField(blank=True, help_text='Comma-separated additional domains for cross-domain measurement.', max_length=400)),
                ('block_paths', models.JSONField(blank=True, default=list, help_text='Path prefixes to never track (e.g. ["/admin/", "/dashboard/"]).')),
                ('bot_patterns', models.JSONField(blank=True, default=list, help_text='User-Agent substrings to never track.')),
                ('dedup_strategy', models.CharField(choices=[('transaction_id', 'By transaction_id (recommended for purchases)'), ('client_window', 'By client_id + event_name + window'), ('off', 'No deduplication')], default='transaction_id', max_length=20)),
                ('dedup_window_minutes', models.PositiveSmallIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking settings',
                'verbose_name_plural': 'Tracking settings',
            },
        ),
        migrations.CreateModel(
            name='GA4EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('user_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error'), ('deduped', 'Deduplicated'), ('disabled', 'Disabled (event firing off)')], db_index=True, default='sent', max_length=12)),
                ('error_message', models.CharField(blank=True, max_length=400)),
                ('fired_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['event_name', '-fired_at'], name='tracking_ga_event_n_a8dcb2_idx'), models.Index(fields=['status', '-fired_at'], name='tracking_ga_status_1ff5e5_idx')],
            },
        ),
    ]
