# Generated by Django 6.0.5 on 2026-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsettings',
            name='consent_override',
            field=models.BooleanField(default=False, help_text='⚠️ COMPLIANCE RISK: when on, every visitor is tracked regardless of their consent decision. Only use on internal staging or non-EU shops. EU consumer-facing shops MUST leave this off.', verbose_name='Ignore visitor consent (debug only)'),
        ),
    ]
