# Generated by Django 6.0.5 on 2026-05-31 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('intent', models.CharField(choices=[('intentional', 'Intentional'), ('experimental', 'Experimental'), ('vendor_specific', 'Vendor-specific')], default='intentional', max_length=32)),
                ('why', models.TextField(help_text='human-written rationale')),
                ('owner', models.CharField(blank=True, max_length=64)),
                ('locked_until', models.DateTimeField(blank=True, help_text='NULL = forever; auto-revisit after', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SI customization',
                'verbose_name_plural': 'SI customizations',
                'db_table': 'si_customization',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SiIngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('signals_emitted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed')], default='ok', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SI ingest job',
                'verbose_name_plural': 'SI ingest jobs',
                'db_table': 'si_ingest_job',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['collector', '-started_at'], name='si_job_coll_start_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('error_log', 'Error log'), ('csp', 'CSP violation'), ('slow_query', 'Slow query'), ('web_vital', 'Web vital'), ('cart_abandon', 'Cart abandon'), ('zero_search', 'Zero-result search'), ('cve', 'CVE advisory'), ('dep', 'Dependency advisory'), ('lighthouse', 'Lighthouse regression'), ('dead_link', 'Dead link'), ('seo_gap', 'SEO gap'), ('code_quality', 'Code-quality finding'), ('upstream_drift', 'Upstream drift')], db_index=True, max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('severity', models.SmallIntegerField(default=50, help_text='0-100')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SI signal',
                'verbose_name_plural': 'SI signals',
                'db_table': 'si_signal',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source', '-occurred_at'], name='si_sig_src_occur_idx'), models.Index(fields=['fingerprint', '-occurred_at'], name='si_sig_fp_occur_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_class', models.CharField(db_index=True, max_length=64)),
                ('match_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('reason', models.TextField(help_text='required from rejector')),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = forever', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SI suppression rule',
                'verbose_name_plural': 'SI suppression rules',
                'db_table': 'si_suppression',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_column='class', db_index=True, help_text='one of the 16 issue classes (seo_gap, dep_bump, …)', max_length=64)),
                ('title', models.CharField(help_text='imperative, ≤ 80 chars', max_length=200)),
                ('rationale', models.TextField(blank=True, help_text='LLM-written, cites signal_ids')),
                ('confidence', models.DecimalField(decimal_places=3, help_text='0.000–1.000', max_digits=4)),
                ('impact_score', models.IntegerField(default=0, help_text='impact × feasibility × evidence')),
                ('evidence_signal_ids', models.JSONField(blank=True, default=list, help_text='list[int] — FK to SiSignal')),
                ('proposed_action', models.JSONField(blank=True, default=dict, help_text='{kind, files, patch, test_command}')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('auto_applied', 'Auto-applied'), ('in_pr', 'In PR'), ('merged', 'Merged'), ('rejected', 'Rejected'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], db_index=True, default='proposed', max_length=16)),
                ('pr_url', models.CharField(blank=True, max_length=300)),
                ('actor', models.CharField(blank=True, max_length=64)),
                ('model_id', models.CharField(blank=True, help_text='LLM model + version', max_length=64)),
                ('tokens_used', models.IntegerField(default=0)),
                ('is_customization_safe', models.BooleanField(default=True, help_text='False blocks auto-apply when the file is customised')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='morph_self_improvement.sisuppression')),
            ],
            options={
                'verbose_name': 'SI recommendation',
                'verbose_name_plural': 'SI recommendations',
                'db_table': 'si_recommendation',
                'ordering': ['-impact_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('detect', 'Detect'), ('propose', 'Propose'), ('gate', 'Safety gate'), ('execute', 'Execute'), ('verify', 'Verify'), ('rollback', 'Rollback')], max_length=16)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('blocked', 'Blocked by safety boundary'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sandbox_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='morph_self_improvement.sirecommendation')),
            ],
            options={
                'verbose_name': 'SI action log entry',
                'verbose_name_plural': 'SI action log',
                'db_table': 'si_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recommendation', 'phase'], name='si_act_rec_phase_idx'), models.Index(fields=['outcome', '-created_at'], name='si_act_outcome_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sisuppression',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__isnull', True)), fields=('match_class', 'match_fingerprint'), name='si_supp_unique_active'),
        ),
        migrations.AddIndex(
            model_name='sirecommendation',
            index=models.Index(fields=['status', '-impact_score'], name='si_rec_status_score_idx'),
        ),
        migrations.AddIndex(
            model_name='sirecommendation',
            index=models.Index(fields=['class_name', 'status'], name='si_rec_class_status_idx'),
        ),
    ]
