# Generated by Django 6.0.5 on 2026-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_self_improvement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisignal',
            name='source',
            field=models.CharField(choices=[('error_log', 'Error log'), ('csp', 'CSP violation'), ('slow_query', 'Slow query'), ('web_vital', 'Web vital'), ('cart_abandon', 'Cart abandon'), ('zero_search', 'Zero-result search'), ('cve', 'CVE advisory'), ('dep', 'Dependency advisory'), ('lighthouse', 'Lighthouse regression'), ('dead_link', 'Dead link'), ('seo_gap', 'SEO gap'), ('code_quality', 'Code-quality finding'), ('upstream_drift', 'Upstream drift'), ('agent_failure', 'Linda failure'), ('agent_dissent', 'Linda dissent'), ('agent_skill_health', 'Linda skill health')], db_index=True, max_length=64),
        ),
    ]
