# Generated by Django 6.0.5 on 2026-07-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_self_improvement', '0002_alter_sisignal_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirecommendation',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='stable (class, cluster) hash — dedup guard against nightly re-propose', max_length=128),
        ),
        migrations.AlterField(
            model_name='sirecommendation',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('auto_applied', 'Auto-applied (queued)'), ('applied', 'Applied'), ('in_pr', 'In PR'), ('merged', 'Merged'), ('rejected', 'Rejected'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], db_index=True, default='proposed', max_length=16),
        ),
    ]
