# Generated by Django 6.0.5 on 2026-06-01 02:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal label shown in the dashboard list. Not shown to shoppers.', max_length=120)),
                ('heading', models.CharField(blank=True, help_text='Shopper-facing carousel heading, e.g. "Picked for you".', max_length=160)),
                ('slot', models.CharField(choices=[('home_above_grid', 'Home — above the grid'), ('home_below_grid', 'Home — below the grid'), ('pdp_below_price', 'Product page — below price'), ('pdp_below_form', 'Product page — below add-to-cart'), ('pdp_above_long_description', 'Product page — above description'), ('cart_summary_extra', 'Cart — order summary'), ('global_below_body', 'Every page — end of body')], db_index=True, help_text='Where on the storefront this block renders.', max_length=40)),
                ('strategy', models.CharField(choices=[('for_you', 'For you (personalized blend)'), ('manual', 'Manual / rule (filtered catalog)'), ('recently_viewed', 'Recently viewed'), ('related', 'Related to this product'), ('bought_together', 'Frequently bought together')], default='for_you', help_text='How products are chosen.', max_length=20)),
                ('limit', models.PositiveSmallIntegerField(default=4, help_text='Maximum number of products to show (1–24).')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=50, help_text='Render order within a slot — lower shows first.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Restrict to products carrying any of these tag names, e.g. ["sale", "new"].')),
                ('metafield_key', models.CharField(blank=True, help_text='Restrict to products with this metafield key (requires the metafields plugin).', max_length=120)),
                ('metafield_value', models.CharField(blank=True, help_text='…and this metafield value. Leave blank to match any value for the key.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Restrict to these categories (plus their primary/additional listings).', related_name='dynamic_blocks', to='catalog.category')),
            ],
            options={
                'ordering': ['slot', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['slot', 'enabled', 'sort_order'], name='dynblock_slot_enabled_idx')],
            },
        ),
    ]
