# Generated by Django 6.0.5 on 2026-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_products', '0003_banditarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicblock',
            name='strategy',
            field=models.CharField(choices=[('for_you', 'For you (personalized blend)'), ('manual', 'Manual / rule (filtered catalog)'), ('recently_viewed', 'Recently viewed'), ('related', 'Related to this product'), ('bought_together', 'Frequently bought together'), ('probability_grid', 'Dynamic Probability Grid'), ('autopilot', 'Autopilot (self-optimizing, per-visitor)')], default='for_you', help_text='How products are chosen.', max_length=20),
        ),
    ]
