# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='media_media_kind_9bddcb_idx',
            old_name='media_media_kind_b8f31a_idx',
        ),
    ]
