# Generated by Django 6.0.5 on 2026-06-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_media_media_kind_b8f31a_idx_media_media_kind_9bddcb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, help_text='Caption / long description. Surfaces in galleries and SEO metadata.'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(blank=True, help_text='Display name / SEO title. Falls back to the filename when blank.', max_length=200),
        ),
    ]
