# Generated by Django 6.0.4 on 2026-04-24 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storechannel')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(db_index=True, max_length=80)),
                ('granularity', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], db_index=True, max_length=10)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.storechannel')),
            ],
            options={
                'indexes': [models.Index(fields=['metric', 'granularity', '-bucket'], name='observabili_metric_1aea1e_idx'), models.Index(fields=['channel', 'metric', '-bucket'], name='observabili_channel_5d1b9a_idx')],
                'unique_together': {('channel', 'metric', 'granularity', 'bucket')},
            },
        ),
    ]
