# Generated by Django 6.0.5 on 2026-10-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='merchantmetric',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='merchantmetric',
            name='observabili_metric_1aea1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='merchantmetric',
            name='observabili_channel_5d1b9a_idx',
        ),
        migrations.DeleteModel(
            name='MerchantMetric',
        ),
    ]
