# Generated by Django 6.0.6 on 2026-06-12 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Consolidates onto the canonical orders.ReturnRequest.

    Dropping the parallel ReturnRequest/ReturnItem tables is safe: the
    plugin shipped with no views/services, so no code path ever wrote a
    row to them (verified before this change — nothing imports
    returns_portal.models anywhere).
    """


    dependencies = [
        ("orders", "0011_order_payment_gateway"),
        ("returns_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="returnrequest",
            name="order",
        ),
        # Retarget the FK from the old bigint-PK ReturnRequest to the uuid-PK
        # orders.ReturnRequest. Postgres can't cast bigint->uuid, so drop + re-add
        # instead of AlterField (the returnfeedback table is empty — returns_portal
        # is brand new, verified 0 rows on prod before this change).
        migrations.RemoveField(
            model_name="returnfeedback",
            name="request",
        ),
        migrations.AddField(
            model_name="returnfeedback",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_feedback",
                to="orders.returnrequest",
            ),
        ),
        migrations.CreateModel(
            name="ReturnResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("exchange", "Exchange"),
                            ("store_credit", "Store credit"),
                        ],
                        default="exchange",
                        max_length=12,
                    ),
                ),
                ("exchange_choices", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_resolution",
                        to="orders.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ReturnItem",
        ),
        migrations.DeleteModel(
            name="ReturnRequest",
        ),
    ]
