# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metafields', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metafield',
            new_name='metafields__content_d5304f_idx',
            old_name='metafields__content_b3f0a2_idx',
        ),
        migrations.RenameIndex(
            model_name='metafield',
            new_name='metafields__namespa_f79d66_idx',
            old_name='metafields__namespa_4c19e7_idx',
        ),
    ]
