# Generated by Django 6.0.5 on 2026-07-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('plugin', models.CharField(max_length=80)),
                ('surface', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day', 'plugin'],
                'indexes': [models.Index(fields=['plugin', '-day'], name='feature_ado_plugin_a0f0f6_idx')],
                'unique_together': {('day', 'plugin', 'surface')},
            },
        ),
    ]
