# Generated by Django 6.0.5 on 2026-05-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
