# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_9e6203_idx',
            old_name='notif_cente_user_id_d18e3c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7cd1_idx',
            old_name='notif_cente_user_id_2b04d6_idx',
        ),
    ]
