# Generated by Django 6.0.5 on 2026-08-20 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_label', models.CharField(blank=True, help_text='Name/email captured at submit time, so the ticket still says who reported it after the account is gone.', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/')),
                ('screenshot_skipped_reason', models.CharField(blank=True, help_text='Why no image: declined, unsupported, too_large, failed. Distinguishes "chose not to" from "we lost it".', max_length=200)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=300)),
                ('viewport', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('client_errors', models.JSONField(blank=True, default=list, help_text='Recent JS errors from the browser at report time.')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Version, request id, and recent server-side ErrorEvent rows.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
