# Generated by Django 6.0.5 on 2026-06-28 13:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('schedule_cron', models.CharField(blank=True, help_text='Cron format for automated delivery', max_length=100)),
                ('date_range_days', models.PositiveIntegerField(default=30)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomEventConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('css_selector', models.CharField(blank=True, help_text='CSS selector to track clicks/forms', max_length=255)),
                ('url_pattern', models.CharField(blank=True, help_text='Regex for matching specific URLs', max_length=255)),
                ('event_kind', models.CharField(choices=[('pageview', 'Page view'), ('product_view', 'Product view'), ('search', 'Search'), ('cart', 'Cart event'), ('checkout', 'Checkout event'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('signup', 'Signup'), ('login', 'Login'), ('agent_run', 'Agent run'), ('error', 'Error'), ('custom', 'Custom'), ('click', 'Button Click'), ('form_submit', 'Form Submission'), ('scroll', 'Scroll Depth')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Interaction duration in ms', null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='error_context',
            field=models.JSONField(blank=True, default=dict, help_text='Stack trace, API failure details'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Used for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='is_realtime',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for real-time stream ingestion'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='scroll_depth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percentage 0-100', null=True),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='cross_device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymized ID for cross-device tracking', max_length=128),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='device_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Browser, OS, screen size, network conditions'),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='geo_location',
            field=models.JSONField(blank=True, default=dict, help_text='Country, region, city from IP'),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='is_consented',
            field=models.BooleanField(default=False, help_text='GDPR/CCPA consent status'),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='kind',
            field=models.CharField(choices=[('pageview', 'Page view'), ('product_view', 'Product view'), ('search', 'Search'), ('cart', 'Cart event'), ('checkout', 'Checkout event'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('signup', 'Signup'), ('login', 'Login'), ('agent_run', 'Agent run'), ('error', 'Error'), ('custom', 'Custom'), ('click', 'Button Click'), ('form_submit', 'Form Submission'), ('scroll', 'Scroll Depth')], db_index=True, default='custom', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['is_realtime', '-created_at'], name='analytics_a_is_real_5ce9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['cross_device_id', '-last_seen_at'], name='analytics_a_cross_d_b9f68f_idx'),
        ),
    ]
