# Generated by Django 6.0.5 on 2026-06-12 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
        ('inventory', '0002_backinstocksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockoutAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=10)),
                ('days_of_cover', models.FloatField(blank=True, null=True)),
                ('daily_velocity', models.FloatField(default=0)),
                ('suggested_reorder_qty', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockout_alerts', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['days_of_cover'],
                'indexes': [models.Index(fields=['status', 'days_of_cover'], name='inventory_s_status_ddcca8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('variant',), name='uniq_open_stockout_alert_per_variant')],
            },
        ),
    ]
