# Generated by Django 6.0.4 on 2026-05-05 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('order_placed', 'Order placed'), ('order_paid', 'Order paid'), ('order_fulfilled', 'Order fulfilled'), ('order_cancelled', 'Order cancelled'), ('refund_issued', 'Refund issued'), ('digital_download', 'Digital downloads'), ('cart_abandoned', 'Cart abandoned'), ('welcome', 'Welcome')], max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField(help_text='Plain-text body. Django template syntax allowed.')),
                ('body_html', models.TextField(blank=True, help_text='Optional HTML body. Falls back to text when blank.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
