# Generated by Django 6.0.5 on 2026-05-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seed_journal_entries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagesection',
            new_name='cms_pagesec_page_id_b2b8c8_idx',
            old_name='cms_pagesec_page_id_4be1c2_idx',
        ),
    ]
