# Generated by Django 6.0.5 on 2026-06-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_cms_pagesec_page_id_4be1c2_idx_cms_pagesec_page_id_b2b8c8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('link', 'Link'), ('mega_categories', 'Genres mega-menu'), ('mega_authors', 'Authors mega-menu')], default='link', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
