# Generated by Django 6.0.5 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_menuitem_kind_alter_menuitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('link', 'Link'), ('mega_categories', 'Genres mega-menu'), ('mega_topics', 'Topics mega-menu'), ('mega_authors', 'Authors mega-menu')], default='link', max_length=20),
        ),
    ]
