# Generated by Django 6.0.4 on 2026-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('order', 'Order'), ('signup', 'Signup'), ('lead_form', 'Lead form'), ('newsletter', 'Newsletter'), ('import', 'Import'), ('manual', 'Manual entry'), ('agent', 'Agent-captured'), ('referral', 'Referral'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
