# Generated by Django 6.0.4 on 2026-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this contact last completed a paid order.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of paid order totals in store currency.', max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid orders. Drives loyalty tiers, segments, RFM.'),
        ),
    ]
