# Generated by Django 6.0.5 on 2026-07-09 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_score', models.PositiveSmallIntegerField(default=1)),
                ('f_score', models.PositiveSmallIntegerField(default=1)),
                ('m_score', models.PositiveSmallIntegerField(default=1)),
                ('segment', models.CharField(choices=[('champions', 'Champions'), ('loyal', 'Loyal'), ('potential', 'Potential'), ('new', 'New'), ('at_risk', 'At risk'), ('lost', 'Lost')], db_index=True, max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_segment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_rfm_segment',
            },
        ),
        migrations.CreateModel(
            name='SegmentMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_segment', models.CharField(blank=True, max_length=20)),
                ('new_segment', models.CharField(max_length=20)),
                ('day', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_segment_migration',
                'ordering': ['-created_at'],
            },
        ),
    ]
