# Generated by Django 6.0.5 on 2026-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, help_text='Optional: if set, redeeming this coupon code at checkout attributes the order to this affiliate without needing a referral click.', max_length=40),
        ),
    ]
