# Generated by Django 6.0.5 on 2026-05-30 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliatelink_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='preferred_payout_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('wire', 'Bank wire'), ('credit', 'Store credit (+10%)')], default='paypal', max_length=12),
        ),
        migrations.AddField(
            model_name='affiliateconversion',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundled_conversions', to='affiliates.affiliatepayout'),
        ),
    ]
