# Generated by Django 6.0.5 on 2026-06-01 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliate_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprogram',
            name='auto_approve_after',
            field=models.PositiveSmallIntegerField(default=0, help_text='Auto-approve a pending affiliate after this many attributed conversions. 0 disables auto-approval (manual only).'),
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='category_commission_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Optional {category_slug: percent} map. Order lines whose product is in a listed category earn that percent instead of the base/tier rate.'),
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='tiers',
            field=models.JSONField(blank=True, default=list, help_text='Optional graduated commission schedule (percent type only). List of {name, min_conversions, percent} ordered by threshold.'),
        ),
        migrations.CreateModel(
            name='AffiliateWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('featured', 'Featured products'), ('category', 'A category'), ('products', 'Specific products')], default='featured', max_length=12)),
                ('category_slug', models.SlugField(blank=True, max_length=200)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('limit', models.PositiveSmallIntegerField(default=6)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (match visitor)')], default='auto', max_length=8)),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('carousel', 'Carousel')], default='grid', max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(db_index=True, max_length=43, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='affiliates.affiliate')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='affiliates.affiliatelink')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['affiliate', 'is_active'], name='affiliates__affilia_45369b_idx')],
            },
        ),
    ]
