# Generated by Django 6.0.5 on 2026-06-13 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_affiliateprogram_auto_approve_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='affiliate_creatives/')),
                ('landing_url', models.CharField(default='/', help_text='The storefront path this creative promotes (e.g. /products/foo/).', max_length=500)),
                ('swipe_copy', models.TextField(blank=True, help_text='Ready-to-paste promo text affiliates can use as-is.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
