# Generated by Django 6.0.5 on 2026-05-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_remove_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoPurchaseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, help_text='Jaccard similarity 0-1; higher = bought together more')),
                ('co_count', models.PositiveIntegerField(help_text='absolute count of co-occurrences in the window')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copurchase_anchors', to='catalog.product')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copurchase_relateds', to='catalog.product')),
            ],
            options={
                'db_table': 'copurchase_score',
                'indexes': [models.Index(fields=['anchor', '-score'], name='copurchase_anchor_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('anchor', 'related'), name='copurchase_unique_pair')],
            },
        ),
    ]
