# Generated by Django 6.0.4 on 2026-06-25 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('code_opt', 'Code Optimization'), ('feat_enh', 'Feature Enhancements'), ('ecom_adv', 'E-commerce Advancements')], db_index=True, max_length=15)),
                ('summary', models.TextField(help_text='A short scannable summary of the report.')),
                ('content', models.TextField(help_text='Markdown-formatted deep dive report.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='morpheus_brain.dailyreport')),
            ],
        ),
    ]
