# Generated by Django 6.0.5 on 2026-06-28 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpheus_brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainBriefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Short scannable lead.')),
                ('content', models.TextField(help_text='Long-form Markdown advisory briefing.')),
                ('generated_by', models.CharField(blank=True, default='', help_text='Provider · model that wrote it.', max_length=160)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
