# Generated by Django 6.0.5 on 2026-05-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_points', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pointstransaction',
            new_name='loyalty_poi_custome_2795dc_idx',
            old_name='loyalty_poi_custome_8d5d12_idx',
        ),
    ]
