# Generated by Django 6.0.5 on 2026-05-31 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_points', '0002_rename_loyalty_poi_custome_8d5d12_idx_loyalty_poi_custome_2795dc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('min_revenue', models.DecimalField(decimal_places=2, help_text='Trailing 12-month revenue threshold (in shop currency)', max_digits=12)),
                ('rank', models.PositiveSmallIntegerField(help_text='Higher = better tier; used to sort + compare')),
                ('perks', models.JSONField(blank=True, default=dict, help_text='{free_shipping_above, points_multiplier, early_access}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_tier',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_score', models.PositiveSmallIntegerField(help_text='1-5; 5=most recent')),
                ('f_score', models.PositiveSmallIntegerField(help_text='1-5; 5=most frequent')),
                ('m_score', models.PositiveSmallIntegerField(help_text='1-5; 5=biggest spender')),
                ('composite', models.CharField(db_index=True, max_length=3)),
                ('segment', models.CharField(choices=[('champion', 'Champion'), ('loyal', 'Loyal customer'), ('promising', 'Promising'), ('at_risk', 'At risk'), ('hibernating', 'Hibernating'), ('lost', 'Lost'), ('new', 'New customer')], db_index=True, max_length=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_customer_rfm',
            },
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_12m', models.DecimalField(decimal_places=2, default=0, help_text='Cached trailing 12-month revenue for this customer', max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tier', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty_points.loyaltytier')),
            ],
            options={
                'db_table': 'loyalty_customer_tier',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('qualifying_order_number', models.CharField(blank=True, default='', max_length=40)),
                ('referrer_reward_points', models.PositiveIntegerField(default=0)),
                ('referee_reward_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_referral',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('referrer', 'referee'), name='loyalty_referral_unique_pair')],
            },
        ),
    ]
