# Generated by Django 6.0.4 on 2026-04-24 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('cart.calculate_total', 'Cart Total'), ('product.calculate_price', 'Product Price'), ('order.validate', 'Order Validation'), ('shipping.rate', 'Shipping Rate'), ('discount.apply', 'Discount Application'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python_safe', 'Sandboxed Python')], default='python_safe', max_length=20)),
                ('source', models.TextField(help_text='Function body. Must define `run(input)`.')),
                ('capabilities', models.JSONField(default=list, help_text='Capability strings the runtime exposes to this function.')),
                ('timeout_ms', models.PositiveIntegerField(default=200, help_text='Soft execution time limit. Hard kill at 4x this value.')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Lower runs first when multiple functions target the same hook.')),
                ('last_error', models.TextField(blank=True)),
                ('last_run_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('invocation_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Channel this function applies to. Null = applies to all channels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='core.storechannel')),
            ],
            options={
                'ordering': ['target', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('input_summary', models.JSONField(default=dict)),
                ('output_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='functions.function')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='function',
            index=models.Index(fields=['target', 'is_enabled'], name='functions_f_target_babee4_idx'),
        ),
        migrations.AddIndex(
            model_name='function',
            index=models.Index(fields=['channel', 'target', 'is_enabled'], name='functions_f_channel_880461_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('channel', 'target', 'name')},
        ),
        migrations.AddIndex(
            model_name='functioninvocation',
            index=models.Index(fields=['function', '-created_at'], name='functions_f_functio_62bad8_idx'),
        ),
    ]
