# Generated by Django 6.0.5 on 2026-05-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='target',
            field=models.CharField(choices=[('cart.calculate_breakdown', 'Cart Breakdown'), ('cart.calculate_total', 'Cart Total (deprecated)'), ('product.calculate_price', 'Product Price'), ('order.validate', 'Order Validation'), ('shipping.rate', 'Shipping Rate'), ('discount.apply', 'Discount Application'), ('custom', 'Custom')], db_index=True, max_length=50),
        ),
    ]
