# Generated by Django 6.0.6 on 2026-06-21 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0005_bookableservice_duration_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region', models.CharField(blank=True, choices=[('kotor', 'Kotor Bay'), ('budva', 'Budva Riviera'), ('durmitor', 'Durmitor & the North'), ('skadar', 'Lake Skadar'), ('podgorica', 'Podgorica'), ('ulcinj', 'Ulcinj & the south coast'), ('tivat', 'Tivat & Luštica'), ('cetinje', 'Cetinje & the Old Royal Capital'), ('other', 'Elsewhere in Montenegro')], db_index=True, default='', max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
