# Generated by Django 6.0.6 on 2026-06-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0006_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableservice',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='[{"q": "...", "a": "..."}] — shown as "Guest questions".'),
        ),
        migrations.AddField(
            model_name='place',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('coastal', 'Coastal'), ('mountains', 'Mountains'), ('national_parks', 'National Parks'), ('cultural', 'Cultural Sites'), ('lakes', 'Lakes & Rivers'), ('cities', 'Cities & Towns')], db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiences/gallery/')),
                ('alt', models.CharField(blank=True, default='', max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_marketplace.bookableservice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
