# Generated by Django 6.0.4 on 2026-07-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0007_bookableservice_faqs_place_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableservice',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "detail": "..."}]'),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='listing_kind',
            field=models.CharField(choices=[('experience', 'Experience'), ('product', 'Product')], db_index=True, default='experience', help_text='Experience (bookable by date) or product (quantity + enquiry).', max_length=12),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='meeting_point',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='what_to_bring',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
