# Generated by Django 6.0.4 on 2026-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0009_addon_pricingtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='tier_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tier_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
