# Generated by Django 6.0.4 on 2026-07-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0010_booking_addons_booking_tier_breakdown_enquiry_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='[{"q": "...", "a": "..."}] — on-page FAQ + FAQPage JSON-LD.'),
        ),
        migrations.AddField(
            model_name='place',
            name='good_for',
            field=models.JSONField(blank=True, default=list, help_text='["families", "couples", ...] — audience pills.'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='overview',
            field=models.TextField(blank=True, default='', help_text='Extended editorial body, shown below the lead description.'),
        ),
        migrations.AddField(
            model_name='place',
            name='quick_facts',
            field=models.JSONField(blank=True, default=list, help_text='[{"label": "...", "value": "..."}] — quick-facts strip.'),
        ),
    ]
