# Generated by Django 6.0.4 on 2026-07-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0011_place_faqs_place_good_for_place_latitude_and_more'),
        ('booking_marketplace', '0011_property_propertyimage_roomtype_staybooking_and_more'),
    ]

    operations = [
    ]
