# Generated by Django 6.0.4 on 2026-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0012_merge_20260704_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='external_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"label": "...", "url": "..."}] — outbound authoritative resources (UNESCO, tourism boards, national parks).'),
        ),
        migrations.AddField(
            model_name='place',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='[{"heading": "...", "body": "..."}] — extended editorial blocks shown after the map (deep-dive content).'),
        ),
    ]
