# Generated by Django 6.0.4 on 2026-08-10 23:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_marketplace', '0013_place_external_links_place_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(blank=True, choices=[('music', 'Music & festivals'), ('culture', 'Culture & arts'), ('food', 'Food & wine'), ('tradition', 'Tradition & carnival'), ('sport', 'Sport & outdoors')], db_index=True, default='', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('kotor', 'Kotor Bay'), ('budva', 'Budva Riviera'), ('durmitor', 'Durmitor & the North'), ('skadar', 'Lake Skadar'), ('podgorica', 'Podgorica'), ('ulcinj', 'Ulcinj & the south coast'), ('tivat', 'Tivat & Luštica'), ('cetinje', 'Cetinje & the Old Royal Capital'), ('other', 'Elsewhere in Montenegro')], db_index=True, default='', max_length=20)),
                ('venue', models.CharField(blank=True, default='', max_length=160)),
                ('when_label', models.CharField(blank=True, default='', help_text='e.g. "Early February", "Mid-July"', max_length=80)),
                ('month', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='1–12, 0 = unset')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_annual', models.BooleanField(default=True, help_text='Recurs every year.')),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list, help_text="[{'q':…, 'a':…}]")),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('official_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, help_text='Destination this event belongs to, when there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='booking_marketplace.place')),
            ],
            options={
                'ordering': ['month', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'month'], name='booking_mar_is_acti_62f177_idx'), models.Index(fields=['region', 'is_active'], name='booking_mar_region_242aa5_idx')],
            },
        ),
    ]
