# Generated by Django 6.0.5 on 2026-07-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_order_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64)),
                ('trees', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_tree_pledge', to='orders.order')),
            ],
            options={
                'verbose_name': 'Tree pledge',
                'verbose_name_plural': 'Tree pledges',
                'ordering': ['-created_at'],
            },
        ),
    ]
