# Generated by Django 6.0.4 on 2026-04-24 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('started_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('counts', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('magento', 'Magento'), ('bigcommerce', 'BigCommerce'), ('csv', 'CSV')], db_index=True, max_length=20)),
                ('source_id', models.CharField(db_index=True, max_length=200)),
                ('dest_app', models.CharField(max_length=100)),
                ('dest_model', models.CharField(max_length=100)),
                ('dest_pk', models.CharField(db_index=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'dest_model', '-last_imported_at'], name='importers_s_source_ad11c1_idx')],
                'unique_together': {('source', 'source_id', 'dest_model')},
            },
        ),
    ]
