# Generated by Django 6.0.5 on 2026-06-09 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_product_additional_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='audiobooks/samples/')),
                ('narrator', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('uploaded', 'Uploaded'), ('elevenlabs', 'ElevenLabs')], default='uploaded', max_length=12)),
                ('status', models.CharField(choices=[('none', 'None'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='none', max_length=12)),
                ('elevenlabs_voice_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='catalog.productvariant')),
            ],
        ),
    ]
