# Generated by Django 6.0.5 on 2026-06-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='source_pdf',
            field=models.FileField(blank=True, help_text='Book PDF used as the narration source for ElevenLabs generation.', null=True, upload_to='audiobooks/source/'),
        ),
    ]
