# Generated by Django 6.0.4 on 2026-04-25 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='default', max_length=100)),
                ('account_id', models.CharField(blank=True, max_length=64)),
                ('api_token', models.CharField(help_text='Cloudflare API token with Zone:Cache Purge + Zone:DNS:Edit scopes.', max_length=256)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CloudflareZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_id', models.CharField(db_index=True, max_length=64)),
                ('domain', models.CharField(db_index=True, max_length=200)),
                ('auto_purge_on_product_update', models.BooleanField(default=True)),
                ('auto_purge_on_collection_update', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_purge_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='cloudflare.cloudflareaccount')),
                ('channel', models.ForeignKey(blank=True, help_text='Optional StoreChannel scope. Null = applies to all channels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloudflare_zones', to='core.storechannel')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('account', 'zone_id')},
            },
        ),
        migrations.CreateModel(
            name='CacheInvalidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('urls', 'URLs'), ('tags', 'Cache Tags'), ('hosts', 'Hosts'), ('purge_everything', 'Purge Everything')], max_length=20)),
                ('targets', models.JSONField(default=list, help_text='URLs / tags / hosts purged.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('triggered_by', models.CharField(blank=True, max_length=120)),
                ('response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalidations', to='cloudflare.cloudflarezone')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zone', '-created_at'], name='cloudflare__zone_id_58c4ff_idx')],
            },
        ),
    ]
