# Generated by Django 6.0.4 on 2026-04-26 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=64)),
                ('field', models.CharField(db_index=True, max_length=80)),
                ('language_code', models.CharField(db_index=True, help_text='BCP-47 short code, e.g. "es", "fr-CA".', max_length=10)),
                ('value', models.TextField()),
                ('is_machine_translated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'language_code'], name='morph_i18n__content_cad83d_idx'), models.Index(fields=['language_code', 'field'], name='morph_i18n__languag_4e4f4a_idx')],
                'unique_together': {('content_type', 'object_id', 'field', 'language_code')},
            },
        ),
    ]
